// Generated by scripts/gen-data.ts from the game archive tables. Do not edit.

/** Quest id and quest_baseinfo_ex_data.AdvisedPWR, in quest counter order, 166 quests. */
export const QUEST_COUNTER: readonly (readonly [id: string, pwr: number])[] = [
  ["00401310", 200], // easy Bash the Goblin Hordes
  ["00401303", 300], // easy Worried about Papa
  ["00401315", 300], // easy Protect Our Woods
  ["00401305", 400], // easy Fort Fumigation
  ["00401316", 400], // easy Tomorrow's Prayers
  ["00401306", 500], // easy Defeat—*wheeze*—Goblin Boss
  ["00401301", 600], // easy Make Our Skies Safe Again
  ["00401311", 800], // easy Guard Our Hometown
  ["00402314", 1000], // normal Spare the Rod, Spoil the Valley
  ["00402315", 1200], // normal Eye Have a Problem
  ["00402316", 1400], // normal Only You Can Prevent Forest Flyers
  ["00402313", 1500], // normal Saga Grande: The Beginning
  ["00402301", 1600], // normal Rilla Done Did It
  ["00402302", 1600], // normal Golemology 101: Desert Golems
  ["00402310", 1800], // normal Dagger Really Done Did It
  ["00402308", 2000], // normal Sweep the Volcano
  ["00402304", 2400], // normal On the Front Lines
  ["00402306", 2400], // normal I See a Bloody Vision
  ["00402312", 2600], // normal The Saga Continues: Ice
  ["00402309", 2800], // normal The Saga Continues: Fire
  ["00403301", 3000], // hard Rule the Skies
  ["00403303", 3000], // hard Unthinning the Troops
  ["00403302", 3200], // hard The Juice of Jealousy
  ["00403201", 3400], // hard Delts of Our Lives
  ["00403307", 3400], // hard Protect the Rep
  ["00403308", 3600], // hard Collector's Digest
  ["00403311", 3600], // hard I See a Flaming Vision
  ["00403202", 3800], // hard Hide and Chic
  ["00403309", 3800], // hard Looming Tower, Leering Eye
  ["00403312", 3800], // hard Drumsticks au Griffin
  ["00404101", 4200], // very hard Wings of Antiquity
  ["00404315", 4200], // very hard Seeds of Trouble
  ["00404316", 4400], // very hard A Bone to Peak
  ["00404317", 4400], // very hard Absolutely No Trespassers!
  ["00404204", 4600], // very hard Dark Refrain
  ["00404313", 4800], // very hard Golemology 102: Volcanic Golems
  ["00404309", 5000], // very hard No One Likes Leftovers
  ["00404310", 5000], // very hard I See a Deathly Vision
  ["00404311", 5000], // very hard The Next Hot Topic
  ["00405101", 5500], // extreme License to Thrill
  ["00405309", 5500], // extreme Assault Formation!
  ["00405310", 5800], // extreme Great Goblins of Fire
  ["00405311", 5800], // extreme Shedding Light on the Pillar
  ["00405201", 6000], // extreme Saga Illustrated: The Beginning
  ["00405206", 6000], // extreme General Investigation: Gallanza
  ["00405207", 6000], // extreme General Investigation: Maglielle
  ["00405202", 6500], // extreme Learning from the Past
  ["00405203", 6500], // extreme Saga Illustrated: Inferno
  ["00405208", 7000], // extreme General Investigation: Id
  ["00405302", 7000], // extreme Wings of Conflagration
  ["00405303", 7000], // extreme Wings of Upheaval
  ["00405304", 7000], // extreme Wings of the Storm
  ["00405305", 7000], // extreme Wings of Rime
  ["00405205", 7200], // extreme To Know the Unknowable
  ["00405308", 7200], // extreme Gulp... So These Are the Rumored Monsters
  ["00406357", 7200], // maniac Death, Taxes, and Goblins
  ["00406358", 7200], // maniac Icy Eye on the Holy Prize
  ["00406359", 7200], // maniac Rumble in the Desert
  ["00406361", 7200], // maniac Slimepede
  ["00406363", 7200], // maniac (unnamed)
  ["00406365", 7200], // maniac Armor Is Best Served Cold
  ["00406366", 7200], // maniac A Heated Rivalry
  ["00406325", 7400], // maniac Hope in the Machine
  ["00406355", 7400], // maniac Golemology 103: Forest Golems
  ["00406356", 7400], // maniac A New Breed
  ["00406360", 7400], // maniac I See a Grim Vision
  ["00406364", 7400], // maniac Throw a Smith a Bone
  ["00406353", 7800], // maniac Know Your Enemy
  ["00406324", 8000], // maniac Revenge of the Hordes
  ["00406327", 8000], // maniac Hallowed Be Thy Ground
  ["00406331", 8000], // maniac The Saga Continues: Wind
  ["00406351", 8000], // maniac Roost and Reign
  ["00406352", 8000], // maniac Boss Done Wants It Did
  ["00406354", 8000], // maniac Serenity Upon the Mount
  ["00406332", 8200], // maniac Saga Illustrated: Crystal
  ["00406337", 8200], // maniac Id Bears Repeating
  ["00406334", 8500], // maniac The Saga Continues: Silver
  ["00406335", 8500], // maniac Saga Illustrated: Veil
  ["00406330", 8800], // maniac The Saga Continues: Earth
  ["00406323", 9000], // maniac I See a Chromatic Vision
  ["00406333", 9000], // maniac Saga Illustrated: Hellfire
  ["00406338", 10000], // maniac Saga Grande: Happily Ever After
  ["00406367", 10000], // maniac (unnamed)
  ["00406339", 11000], // maniac (unnamed)
  ["00407101", 11000], // proud The Final Report
  ["00407301", 12000], // proud Blazing Trial
  ["00407302", 12000], // proud Grounded Trial
  ["00407303", 12000], // proud Stormy Trial
  ["00407304", 12000], // proud Frigid Trial
  ["00407305", 14000], // proud Worst Vacation Ever
  ["00407306", 14000], // proud Trade Barriers
  ["00407307", 14000], // proud Melting Pot of Hostility
  ["00407308", 14000], // proud Banquet of Ice and Corpses
  ["00407309", 14000], // proud For a Freer Folca
  ["00407310", 16000], // proud A Quest of Fire and Earth
  ["00407311", 16000], // proud A Quest of Frost and Storm
  ["00407312", 17000], // proud The Wolf and the Veil
  ["00407313", 17000], // proud Calamity Incarnate
  ["00407314", 17000], // proud As Fierce as the Silver Wolf
  ["00407315", 17000], // proud Memories of Fire
  ["00407316", 17000], // proud Thunderbolts and Lightning
  ["00407317", 17000], // proud Into the Abyss
  ["00407319", 18000], // proud The Automagod Strikes Back
  ["00407318", 19000], // proud The Tale of Bahamut's Rage
  ["00407322", 19500], // proud Lock Horns
  ["00407320", 21000], // proud The Final Vision
  ["00407324", 22000], // proud Pageant of Might and Magic
  ["00407325", 22000], // proud Zathba's "Volunteers"
  ["00407323", 22500], // proud Dark Swordsman's Nightmare
  ["00407321", 30000], // proud Zero
  ["00408301", 23000], // chaos A Trial of Two Eternities
  ["00408302", 23500], // chaos Jumbo Crab's Title Fight
  ["00408305", 23500], // chaos Sun Blotter
  ["00408306", 23500], // chaos Gray Gear Reverberance
  ["00408308", 23500], // chaos Nightmare Valley
  ["00408311", 23500], // chaos You're Being Watched
  ["00408312", 23500], // chaos In the Depths of Madness
  ["00408314", 23500], // chaos Pilgrims of Self-Delusion
  ["00408310", 25000], // chaos The General Assembly
  ["00408313", 25000], // chaos Spear of the Invincible
  ["00408315", 25000], // chaos One-Woman Army
  ["00409302", 26000], // chaos+ Bestial Earth
  ["00409305", 26000], // chaos+ Bestial Frost
  ["00409308", 26000], // chaos+ Incoming!
  ["00409313", 26000], // chaos+ Bestial Blaze
  ["00409311", 28000], // chaos+ Revenge of the Ooze
  ["00409314", 28000], // chaos+ Shadows of the Past: Sequestration
  ["00409317", 28000], // chaos+ Shadows of the Past: Vitality
  ["00409319", 28000], // chaos+ Shadows of the Past: Dread
  ["00409320", 28000], // chaos+ Bring Light to the World
  ["00409303", 30000], // chaos+ Abandon Hope
  ["00409307", 30000], // chaos+ Permafrost
  ["00409309", 30000], // chaos+ Sephira's Sanguine Glimmer
  ["00409312", 30000], // chaos+ Wildfire
  ["00409315", 30000], // chaos+ Procession of Dragons
  ["0040A302", 32000], // chaos++ Survival of the Fittest
  ["0040A303", 32000], // chaos++ Weight of a Blade
  ["0040A304", 32000], // chaos++ March of Lost Souls
  ["0040A305", 32000], // chaos++ Lightning Strikes Twice
  ["0040A307", 32000], // chaos++ Flavor Blast!
  ["0040A310", 32000], // chaos++ Tectonic Clash
  ["0040A306", 33000], // chaos++ All-Consuming Darkness
  ["0040A321", 33000], // chaos++ Supernatural Appetite for Meat
  ["0040A311", 34000], // chaos++ Terror from the Moon
  ["0040A320", 34000], // chaos++ Roar from the Heavens
  ["0040A301", 34500], // chaos++ New World Order
  ["0040A308", 34500], // chaos++ The Eternal Grind
  ["0040A309", 34500], // chaos++ A Reckoning for the Reckoner
  ["0040A312", 34500], // chaos++ Mazurka of War
  ["0040A313", 34500], // chaos++ A Prayer for Black Wings' Demise
  ["0040A314", 34500], // chaos++ Let Chaos Reign
  ["0040A316", 35000], // chaos++ The Not Forgotten Sky
  ["0040A322", 36000], // chaos++ The Myths Are Real
  ["0040A323", 36000], // chaos++ In the Wrong Hands
  ["0040A324", 36500], // chaos++ The Tempest Rises
  ["0040A325", 36500], // chaos++ Reclusive Vengeance
  ["0040A326", 36500], // chaos++ Four Dragons of the Apocalypse
  ["0040A327", 36500], // chaos++ Rock Around the Clock
  ["0040A328", 37000], // chaos++ An Act of Automagod
  ["0040A329", 37000], // chaos++ Beneath Primeval Wings
  ["0040A330", 37000], // chaos++ Eternal Pride
  ["0040B301", 45000], // infinity On the Threshold of The World
  ["0040B309", 45000], // infinity On the Threshold of Destruction
  ["0040B313", 45000], // infinity On the Threshold of Finality
  ["0040B314", 45000], // infinity On the Threshold of Chaos
  ["0040B316", 46000], // infinity On the Threshold of Provenance
];
