// Generated by scripts/gen-data.ts from the game archive tables. Do not edit.

/** The journal's trophy tabs, base game and Endless Ragnarok together. */
export const TROPHY_TABS = ["story","character","battle","gear","conflux","summons","other"] as const;

export type TrophyTab = (typeof TROPHY_TABS)[number];

/** `badge` rows in SortOrder order: Key, tab, IsEndlessRagnarok, and ReqQuantity, the
 * {0} of the descriptions that have one. 1615 rows. */
export const TROPHIES: readonly (readonly [
  key: number,
  tab: TrophyTab,
  dlc: boolean,
  quantity: number,
])[] = [
  [10, "story", false, 1], // Lift Off
  [0, "story", false, 1], // Sky Voyager
  [1404, "story", false, 1], // (unnamed)
  [1, "story", false, 1], // Visitor from Beyond
  [1405, "story", false, 1], // The Western Frontier
  [2, "story", false, 1], // Savior of the Windswept Isle
  [1406, "story", false, 1], // Tempest on the Horizon
  [3, "story", false, 1], // Pacifier of the Divine Gale
  [1407, "story", false, 1], // Creation of the Stars
  [4, "story", false, 1], // Destroyer of the Armada
  [1408, "story", false, 1], // Skies Forever Blue
  [1418, "story", false, 1], // Sharpshooter
  [1419, "story", false, 12], // Cannon Crusher
  [5, "story", false, 1], // Tamer of the Divine Wolf
  [1409, "story", false, 1], // Shadows in the Snowscape
  [6, "story", false, 1], // Saboteur of the Divine Tower
  [1410, "story", false, 1], // In Search of Hope
  [7, "story", false, 1], // Extinguisher of the Divine Flame
  [1411, "story", false, 1], // Warning Signs
  [8, "story", false, 1], // One with the Blue
  [1412, "story", false, 1], // Relink
  [1420, "story", false, 1], // Child of Darkness and Flames
  [9, "story", false, 1], // Guardian of Seedhollow
  [1413, "story", false, 1], // Opposing Wills
  [11, "story", false, 38], // Eternal Adventurer
  [1397, "story", false, 1], // Id
  [12, "story", false, 41], // Defender of Zegagrande
  [13, "story", false, 41], // Savior of Zegagrande
  [14, "story", false, 41], // Above and Beyond
  [1396, "story", false, 41], // The Ultimate
  [15, "story", false, 41], // Perfectly Heroic
  [16, "story", false, 41], // Hardcore
  [17, "story", false, 1], // Insanity
  [18, "story", false, 1], // Godslayer
  [19, "story", false, 1], // Reunited and It Feels So Good
  [1398, "story", false, 1], // Skybound Heart
  [20, "story", false, 1], // Pro Gamer Moves
  [1421, "story", false, 1], // Primeval Dragon
  [76, "story", false, 1], // Casual Scribe
  [77, "story", false, 15], // Budding Archivist
  [1438, "story", false, 30], // Closer to the Truth
  [78, "story", false, 45], // Truth Seeker
  [79, "story", false, 75], // All-Knowing Librarian
  [80, "story", false, 1], // In a Pinch
  [81, "story", false, 10], // I Like Crabs
  [82, "story", false, 20], // To Crablivion and Beyond
  [1437, "story", false, 20], // Crabs Are Neat
  [83, "story", false, 45], // Head Empty, Just Crabs
  [84, "story", false, 1], // The Hunt Is On
  [85, "story", false, 25], // Look What I Found
  [1439, "story", false, 50], // Treasure Hunter
  [86, "story", false, 75], // What's in the Box?!
  [87, "story", false, 168], // Compulsive Chest Opener
  [1440, "story", false, 10], // Unlocked and Unloaded
  [88, "story", false, 1], // Slime Time
  [89, "story", false, 5], // Slime Hunter
  [90, "story", false, 15], // Goo Away
  [91, "story", false, 25], // Slime's the Limit
  [551, "story", false, 3], // Roy G. Biv
  [552, "story", false, 10], // Legendary Slayer
  [553, "story", false, 13], // Record Holder
  [21, "story", false, 1], // Adept Skyfarer
  [22, "story", false, 1], // Renowned Skyfarer
  [23, "story", false, 1], // Supreme Skyfarer
  [24, "story", false, 1], // Soaring Skyfarer
  [25, "story", false, 1], // Legendary Skyfarer
  [542, "story", false, 1], // To Stand Among Myths
  [26, "story", false, 8], // Up-and-Comer
  [27, "story", false, 12], // Making Waves
  [28, "story", false, 10], // Winds of Change
  [29, "story", false, 9], // Prodigal Rise
  [30, "story", false, 15], // Glorious Skyfaring
  [31, "story", false, 26], // Sent from the Heavens
  [543, "story", false, 20], // To Hell and Back Again
  [32, "story", false, 50], // A Nose for Quests
  [33, "story", false, 100], // Battle-Hardened
  [34, "story", false, 250], // Quest Crusher
  [35, "story", false, 500], // Questing Is My Passion
  [1414, "story", false, 1], // Leave It to Me
  [36, "story", false, 50], // Distinguished
  [37, "story", false, 200], // Celebrated
  [38, "story", false, 500], // Preeminent
  [544, "story", false, 100], // No Quest Unturned
  [545, "story", false, 1], // Overkill
  [546, "story", false, 100], // Peerless Killer
  [547, "story", false, 1], // Speedster
  [548, "story", false, 100], // Incomparable Speed
  [39, "story", false, 10], // Commendable
  [40, "story", false, 100], // Commendabler
  [41, "story", false, 250], // Commendablest
  [43, "story", false, 1], // From Humble Beginnings
  [42, "story", false, 1], // The Dragon Knights
  [44, "story", false, 1], // Windswept Traveler
  [45, "story", false, 5], // Windswept Skyfarer
  [46, "story", false, 15], // Windswept Paragon
  [47, "story", false, 30], // Folca Questpert
  [48, "story", false, 1], // Blooming Traveler
  [49, "story", false, 10], // Blooming Skyfarer
  [50, "story", false, 25], // Blooming Paragon
  [51, "story", false, 50], // Seedhollow Questpert
  [52, "story", false, 1], // A Helpful Neighbor
  [1417, "story", false, 1], // I Try to Help
  [53, "story", false, 20], // Not a Problem!
  [54, "story", false, 50], // Easy as Pie!
  [55, "story", false, 100], // Gimme All Yer Quests!
  [1399, "story", false, 110], // Nothing Is Impossible!
  [56, "story", false, 11], // Unshakeable Bonds
  [58, "story", false, 11], // More than a Knight
  [57, "story", false, 11], // Nautilus Backer
  [59, "story", false, 11], // Smile Maker
  [61, "story", false, 11], // Kharzeda's Hero
  [60, "story", false, 11], // Blooming Maiden
  [67, "story", false, 11], // Forever Pure and Righteous
  [70, "story", false, 11], // Fist of Legend
  [62, "story", false, 11], // Little White Lie
  [69, "story", false, 11], // Slayer of Thousands
  [63, "story", false, 11], // Hero of Grosgard
  [64, "story", false, 11], // Superhero
  [65, "story", false, 11], // New Vassals
  [66, "story", false, 11], // For King and Country
  [71, "story", false, 11], // The Cutest Alchemist
  [68, "story", false, 11], // Fishergod
  [549, "story", false, 11], // That Special Someone
  [550, "story", false, 11], // Fighting Death
  [631, "story", false, 11], // Noblesse Oblige
  [632, "story", false, 11], // Eye Spy
  [668, "story", false, 11], // Inquisitive about the Skies
  [72, "story", false, 11], // Crime Slayer
  [73, "story", false, 5], // Fate Watcher
  [74, "story", false, 10], // Fate Beholder
  [75, "story", false, 15], // Fate Seer
  [1433, "story", false, 1], // A Fateful Encounter
  [1434, "story", false, 1], // A Fateful Farewell
  [1401, "story", false, 19], // Fate Can't Wait
  [190, "character", false, 30], // Getting Good
  [191, "character", false, 60], // Date with Destiny
  [192, "character", false, 80], // Skyblazer
  [193, "character", false, 100], // Racing Across the Sky
  [194, "character", false, 1], // Room for Improvement
  [195, "character", false, 100], // Professional Skyfarer
  [196, "character", false, 100], // Guts and Glory
  [197, "character", false, 1], // Clear Skies Ahead
  [198, "character", false, 30], // Blue Fencer
  [199, "character", false, 60], // Wall of Ice
  [200, "character", false, 80], // Guardian of Promises
  [201, "character", false, 100], // Azure Guardian
  [202, "character", false, 1], // Sword Fanatic
  [203, "character", false, 100], // Can't Handle Cuteness
  [204, "character", false, 100], // Lyria's Guardian
  [205, "character", false, 1], // Unfailing Loyalty
  [206, "character", false, 30], // Rough-and-Tumble Gunner
  [207, "character", false, 60], // Like a Tempest
  [208, "character", false, 80], // Greatest Helmsman in the World
  [209, "character", false, 100], // Into the Brink
  [210, "character", false, 1], // Durationist
  [211, "character", false, 100], // Fun to Tease
  [212, "character", false, 100], // Pessimist
  [213, "character", false, 1], // Going with the Flow
  [214, "character", false, 30], // Little Powerhouse
  [215, "character", false, 60], // Sincere Healer
  [216, "character", false, 80], // Archmage
  [217, "character", false, 100], // Heart of Magic
  [218, "character", false, 1], // Hates to Lose
  [219, "character", false, 100], // Loves to Impress
  [220, "character", false, 100], // Sophisticated Lady
  [221, "character", false, 1], // Genuine Talent
  [230, "character", false, 30], // Twice the Mercenary
  [231, "character", false, 60], // Eagle-Eyed
  [232, "character", false, 80], // Sorrowful Survivor
  [233, "character", false, 100], // Human War Machine
  [234, "character", false, 1], // Soiya!
  [235, "character", false, 100], // Aging Like Wine
  [236, "character", false, 100], // Way of the Macho
  [237, "character", false, 1], // Seasoned Expert
  [222, "character", false, 30], // Iron Maiden
  [223, "character", false, 60], // Dominator
  [224, "character", false, 80], // Rose Queen
  [225, "character", false, 100], // Verdant Garden
  [226, "character", false, 1], // Protector of Lumacie
  [227, "character", false, 100], // Bridging Past and Present
  [228, "character", false, 100], // Io's Confidant
  [229, "character", false, 1], // Fully Blossomed
  [278, "character", false, 30], // Holy Knight
  [279, "character", false, 60], // Brilliant Swordmaster
  [280, "character", false, 80], // Graceful Paladin
  [281, "character", false, 100], // Preeminent Knight of Lumiel
  [282, "character", false, 1], // The Little Knight That Could
  [283, "character", false, 100], // Little Skyfarer's Lunch
  [284, "character", false, 100], // Sword of Lumiel
  [285, "character", false, 1], // Equal to a Thousand Knights
  [302, "character", false, 30], // Mega Punch
  [303, "character", false, 60], // Knuckle Sandwich
  [304, "character", false, 80], // Meteoric Smasher
  [305, "character", false, 100], // History's Mightiest Fist
  [306, "character", false, 1], // Fists Only
  [307, "character", false, 100], // Unparalleled
  [308, "character", false, 100], // Eternally Raging
  [309, "character", false, 1], // These Fists Don't Lie
  [238, "character", false, 30], // Nameless Ghost
  [239, "character", false, 60], // Ectoplasmic
  [240, "character", false, 80], // Ghost Tamer
  [241, "character", false, 100], // Phantom Maiden
  [242, "character", false, 1], // Whipped into Shape
  [243, "character", false, 100], // Relic of the Past
  [244, "character", false, 100], // Between Life and Death
  [245, "character", false, 1], // Under the Winter Moonlight
  [294, "character", false, 30], // Fluttering Dreamer
  [295, "character", false, 60], // Ethereal Fencer
  [296, "character", false, 80], // Purehearted
  [297, "character", false, 100], // Butterfly of Death
  [298, "character", false, 1], // License to Kill
  [299, "character", false, 100], // Napping under the Sun
  [300, "character", false, 100], // Spoiling Them Rotten
  [301, "character", false, 1], // Ephemeral Samurai
  [246, "character", false, 30], // Two Blades Are Better than One
  [247, "character", false, 60], // Royal Blue Knight
  [248, "character", false, 80], // Knight of Ice
  [249, "character", false, 100], // Chivalrous Knight Captain
  [250, "character", false, 1], // Proud Dragon Knight
  [251, "character", false, 100], // Captain of the White Dragons
  [252, "character", false, 100], // Vane's Best Friend
  [253, "character", false, 1], // Forthright and Honorable
  [254, "character", false, 30], // Never without a Smile
  [255, "character", false, 60], // Brave Warrior
  [256, "character", false, 80], // What It Takes to Be a Hero
  [257, "character", false, 100], // Indominable Knight
  [258, "character", false, 1], // I'll Do the Dishes!
  [259, "character", false, 100], // Master Chef
  [260, "character", false, 100], // One for All
  [261, "character", false, 1], // Burgeoning Promise
  [262, "character", false, 30], // Burning Wolf
  [263, "character", false, 60], // Crimson Prince
  [264, "character", false, 80], // Regal Trailblazer
  [265, "character", false, 100], // Lord of Flames
  [266, "character", false, 1], // Sir Burnsalot
  [267, "character", false, 100], // Inextinguishable Flame
  [268, "character", false, 100], // Kingdom Builder
  [269, "character", false, 1], // Great and Noble Leader
  [270, "character", false, 30], // Aggressive Sword Arm
  [271, "character", false, 60], // Dutybound Knight
  [272, "character", false, 80], // Savage Dragoon
  [273, "character", false, 100], // Dragonslayer
  [274, "character", false, 1], // Majesty
  [275, "character", false, 100], // Blade of the Black Dragons
  [276, "character", false, 100], // Slayer of True Dragons
  [277, "character", false, 1], // Devoted to Duty
  [310, "character", false, 30], // Sweet Alchemist
  [311, "character", false, 60], // Inspiring Alchemist
  [312, "character", false, 80], // Genius Alchemist
  [313, "character", false, 100], // Founder of Alchemy
  [314, "character", false, 1], // Once in a Millennia
  [315, "character", false, 100], // Walking Library
  [316, "character", false, 100], // The OG
  [317, "character", false, 1], // Change is the Only Constant
  [286, "character", false, 30], // Vintage Angler
  [287, "character", false, 60], // Hermit with a Sword
  [288, "character", false, 80], // Master Fencer
  [289, "character", false, 100], // Phantasmagoric Swordmaster
  [290, "character", false, 1], // Vagabond
  [291, "character", false, 100], // Old Dogs Can Learn New Tricks
  [292, "character", false, 100], // Big Fish
  [293, "character", false, 1], // One-Stroke Deathbringer
  [581, "character", false, 30], // Arvess's Contractor
  [582, "character", false, 60], // Crimson Lancer
  [583, "character", false, 80], // Explosive Spear
  [584, "character", false, 100], // Resonating with Arvess
  [585, "character", false, 1], // Show Them Our Power!
  [586, "character", false, 100], // Terror from Above
  [587, "character", false, 100], // Blazing Pathos
  [588, "character", false, 1], // Sunset Plover
  [589, "character", false, 30], // Grynoth's Contractor
  [590, "character", false, 60], // Remorseful Scythe
  [591, "character", false, 80], // Sickle Moon
  [592, "character", false, 100], // Resonating with Grynoth
  [593, "character", false, 1], // Watch My Back
  [594, "character", false, 100], // Sabet Odem
  [595, "character", false, 100], // Unbreakable Body
  [596, "character", false, 1], // No Peeking Under the Helmet
  [1588, "character", false, 30], // Seventh Heaven
  [1589, "character", false, 60], // Saber This Moment
  [639, "character", false, 80], // The Northern Lights
  [640, "character", false, 100], // Hearkener of the Boundary
  [641, "character", false, 1], // I Studied the Blade
  [642, "character", false, 100], // Swimming in a Sea of Stars
  [643, "character", false, 100], // Master of Smug
  [644, "character", false, 1], // Star Sword Sovereign
  [1590, "character", false, 30], // Forever Tweyenty
  [1591, "character", false, 60], // Perfect Arc
  [645, "character", false, 80], // Shining Arrow
  [646, "character", false, 100], // Solo Sniper
  [647, "character", false, 1], // Dodge This
  [648, "character", false, 100], // All-Seeing Eye
  [649, "character", false, 100], // Hawkish Bowmaster
  [650, "character", false, 1], // I Never Miss
  [1592, "character", false, 30], // Lightbringer
  [1593, "character", false, 60], // Evangelium
  [672, "character", false, 80], // Fleeting Wings
  [673, "character", false, 100], // Light that Guides the World
  [674, "character", false, 1], // Bittersweet Memories
  [675, "character", false, 100], // Your Fingers Are Delicate
  [676, "character", false, 100], // Nihilist
  [677, "character", false, 1], // The Skies Will Always Be Blue
  [318, "character", false, 30], // Breaker
  [319, "character", false, 60], // Subjugator
  [320, "character", false, 80], // Redeemer
  [321, "character", false, 100], // Destroyer
  [322, "character", false, 1], // A Man of Few Words
  [323, "character", false, 100], // Gone in 90 Seconds
  [324, "character", false, 100], // Judge, Jury, and Executioner
  [325, "character", false, 1], // The Dragon Within
  [696, "character", false, 1], // Captain of the Grandcypher
  [697, "character", false, 1], // I Roll with Katalina
  [698, "character", false, 1], // I Roll with Rackam
  [699, "character", false, 1], // I Roll with Io
  [701, "character", false, 1], // I Roll with Eugen
  [700, "character", false, 1], // I Roll with Rosetta
  [702, "character", false, 1], // I Roll with Charlotta
  [703, "character", false, 1], // I Throw Hands with Ghandagoza
  [704, "character", false, 1], // I Roll with Ferry
  [705, "character", false, 1], // I Roll with Narmaya
  [706, "character", false, 1], // I Roll with Lancelot
  [707, "character", false, 1], // I Roll with Vane
  [708, "character", false, 1], // I Roll with Percival
  [709, "character", false, 1], // I Roll with Siegfried
  [710, "character", false, 1], // I Roll with Cagliostro
  [711, "character", false, 1], // I Roll with Yodarha
  [712, "character", false, 1], // I Roll with Zeta
  [713, "character", false, 1], // I Roll with Vaseraga
  [716, "character", false, 1], // I Roll with Seofon
  [715, "character", false, 1], // I Roll with Tweyen
  [717, "character", false, 1], // I Roll with Sandalphon
  [714, "character", false, 1], // I Roll with Id
  [719, "character", false, 1], // Ultimate Survivor
  [720, "character", false, 1], // Katalina's Deputy
  [721, "character", false, 1], // Rackam's Deputy
  [722, "character", false, 1], // Io's Deputy
  [724, "character", false, 1], // Eugen's Deputy
  [723, "character", false, 1], // Rosetta's Deputy
  [725, "character", false, 1], // Charlotta's Deputy
  [726, "character", false, 1], // Ghandagoza's Disciple
  [727, "character", false, 1], // Ferry's Deputy
  [728, "character", false, 1], // Narmaya's Deputy
  [729, "character", false, 1], // Lancelot's Knight-Errant
  [730, "character", false, 1], // Vane's Knight-Errant
  [731, "character", false, 1], // Percival's Knight-Errant
  [732, "character", false, 1], // Siegfried's Knight-Errant
  [733, "character", false, 1], // Cagliostro's Disciple
  [734, "character", false, 1], // Yodarha's Disciple
  [735, "character", false, 1], // Zeta's Protégé
  [736, "character", false, 1], // Vaseraga's Protégé
  [739, "character", false, 1], // Seofon's Deputy
  [738, "character", false, 1], // Tweyen's Deputy
  [740, "character", false, 1], // Sandalphon's Successor
  [737, "character", false, 1], // Id's Adherent
  [103, "battle", false, 1], // Wind Hunter
  [104, "battle", false, 1], // Wind Primal's Emancipator
  [105, "battle", false, 1], // Water Hunter
  [106, "battle", false, 1], // Water Primal's Emancipator
  [107, "battle", false, 1], // Earth Hunter
  [108, "battle", false, 1], // Earth Primal's Emancipator
  [101, "battle", false, 1], // Fire Hunter
  [102, "battle", false, 1], // Fire Primal's Emancipator
  [109, "battle", false, 1], // Sealed the Calamitous Gates
  [110, "battle", false, 1], // Vanquished the Astral Solstice
  [111, "battle", false, 1], // Felled the Wings of Darkness
  [1395, "battle", false, 1], // Wings of Destruction
  [565, "battle", false, 1], // Pacifier of Vital Wind
  [566, "battle", false, 1], // Tamer of Sequestered Frost
  [567, "battle", false, 1], // Extinguisher of Dreadful Fire
  [570, "battle", false, 1], // Surpassing the Automagod
  [571, "battle", false, 1], // Moonbreaker
  [568, "battle", false, 1], // Surpassing Wings of Darkness
  [569, "battle", false, 1], // Godsbane
  [743, "battle", false, 1], // Shin Versa
  [744, "battle", false, 3], // Destroyer of Worlds
  [745, "battle", false, 1], // World Bahamut
  [572, "battle", false, 1], // Surpassing Dark Rapture
  [573, "battle", false, 1], // Superstar Nova
  [685, "battle", false, 1], // Six-Winged
  [686, "battle", false, 1], // Twelve-Winged
  [112, "battle", false, 15], // Primal Beast Hunter
  [113, "battle", false, 30], // Primal Beast Slayer
  [114, "battle", false, 50], // Primal Terror
  [115, "battle", false, 100], // Primal Undertaker
  [1416, "battle", false, 100], // Primal Beast Punisher
  [574, "battle", false, 50], // Nihilla Exorcist
  [92, "battle", false, 1], // Ancient Assassin
  [554, "battle", false, 1], // Ancient Agonizer
  [93, "battle", false, 1], // Iced Vrazarek
  [555, "battle", false, 1], // Vrazarek Vanquisher
  [95, "battle", false, 1], // Crumbled Corvell
  [557, "battle", false, 1], // Corvell Conqueror
  [96, "battle", false, 1], // Suffocated Elusious
  [558, "battle", false, 1], // Elusious Eradicator
  [94, "battle", false, 1], // Roasted Wilinus
  [556, "battle", false, 1], // Wilinus Warmonger
  [559, "battle", false, 1], // Radis Renouncer
  [97, "battle", false, 1], // Lit Up Evyl
  [560, "battle", false, 6], // Dragon Dreadnaught
  [98, "battle", false, 1], // Power is Power
  [561, "battle", false, 1], // Silver Wolf
  [99, "battle", false, 1], // Superior Collection
  [562, "battle", false, 1], // Sword Veil
  [563, "battle", false, 1], // Zegagrande's Finest
  [100, "battle", false, 1], // Denier of Destiny
  [564, "battle", false, 1], // Brooding Blade
  [665, "battle", false, 1], // Behemoth Slayer
  [666, "battle", false, 50], // Behemoth Eater
  [667, "battle", false, 100], // Ultimate Enlightenment Achieved
  [694, "battle", false, 1], // Beast Mode
  [695, "battle", false, 1], // Moon Exorcist
  [741, "battle", false, 1], // I Stole the Show
  [718, "battle", false, 1], // Battle Master
  [742, "battle", false, 1], // God of War
  [116, "battle", false, 1], // Unleash Hell
  [1426, "battle", false, 10], // No Holding Back
  [117, "battle", false, 50], // Bound for Greatness
  [118, "battle", false, 100], // Blast 'Em
  [119, "battle", false, 500], // Art of War
  [120, "battle", false, 1], // Full Burst!
  [1422, "battle", false, 1], // About to Full Burst
  [1425, "battle", false, 100], // Chain Burst Champion
  [1423, "battle", false, 999999], // Don't Think It Goes Higher Than That
  [121, "battle", false, 50], // Overburst!
  [122, "battle", false, 100], // Bursting with Power
  [123, "battle", false, 500], // Bursting Beyond
  [124, "battle", false, 1], // Let's Link Up
  [125, "battle", false, 50], // Link Master
  [126, "battle", false, 100], // Take My Hand
  [127, "battle", false, 500], // Found the Missing Link
  [128, "battle", false, 1], // It's Linking Time
  [1424, "battle", false, 1], // In Perfect Sync
  [129, "battle", false, 50], // Mind Melding
  [130, "battle", false, 100], // We're Compatible
  [131, "battle", false, 500], // Synchronicity
  [132, "battle", false, 1], // Spirit Breaker
  [1432, "battle", false, 5], // Give Me Something to Break
  [133, "battle", false, 1], // I Got You
  [1427, "battle", false, 5], // Field Medic
  [134, "battle", false, 30], // Lifesaver
  [135, "battle", false, 100], // Phoenix
  [136, "battle", false, 1], // Gimme a Break
  [137, "battle", false, 25], // Skyfarer Smash!
  [138, "battle", false, 100], // We Will Wreck You
  [1428, "battle", false, 50], // It's Called Skill
  [1429, "battle", false, 20], // Buff Buffet
  [1430, "battle", false, 20], // Debuff Deluge
  [1431, "battle", false, 50], // I Will Survive
  [139, "battle", false, 3], // Skybound Captain
  [140, "battle", false, 1], // Gate-Crushing Captain
  [141, "battle", false, 1], // Darkness-Smashing Captain
  [142, "battle", false, 3], // Skybound Guardian
  [143, "battle", false, 1], // Gate-Crushing Guardian
  [144, "battle", false, 1], // Darkness-Smashing Guardian
  [145, "battle", false, 3], // Skybound Helmsman
  [146, "battle", false, 1], // Gate-Crushing Helmsman
  [147, "battle", false, 1], // Darkness-Smashing Helmsman
  [148, "battle", false, 3], // Skybound Mage
  [149, "battle", false, 1], // Gate-Crushing Mage
  [150, "battle", false, 1], // Darkness-Smashing Mage
  [154, "battle", false, 3], // Skybound Sniper
  [155, "battle", false, 1], // Gate-Crushing Sniper
  [156, "battle", false, 1], // Darkness-Smashing Sniper
  [151, "battle", false, 3], // Skybound Rose
  [152, "battle", false, 1], // Gate-Crushing Rose
  [153, "battle", false, 1], // Darkness-Smashing Rose
  [172, "battle", false, 3], // Skybound Holy Knight
  [173, "battle", false, 1], // Gate-Crushing Holy Knight
  [174, "battle", false, 1], // Darkness-Smashing Holy Knight
  [181, "battle", false, 3], // Skybound Brawler
  [182, "battle", false, 1], // Gate-Crushing Brawler
  [183, "battle", false, 1], // Darkness-Smashing Brawler
  [157, "battle", false, 3], // Skybound Ghost
  [158, "battle", false, 1], // Gate-Crushing Ghost
  [159, "battle", false, 1], // Darkness-Smashing Ghost
  [178, "battle", false, 3], // Skybound Butterfly
  [179, "battle", false, 1], // Gate-Crushing Butterfly
  [180, "battle", false, 1], // Darkness-Smashing Butterfly
  [160, "battle", false, 3], // Skybound Twinfang
  [161, "battle", false, 1], // Gate-Crushing Twinfang
  [162, "battle", false, 1], // Darkness-Smashing Twinfang
  [163, "battle", false, 3], // Skybound Champion
  [164, "battle", false, 1], // Gate-Crushing Champion
  [165, "battle", false, 1], // Darkness-Smashing Champion
  [166, "battle", false, 3], // Skybound Lord
  [167, "battle", false, 1], // Gate-Crushing Lord
  [168, "battle", false, 1], // Darkness-Smashing Lord
  [169, "battle", false, 3], // Skybound Dragonslayer
  [170, "battle", false, 1], // Gate-Crushing Dragonslayer
  [171, "battle", false, 1], // Darkness-Smashing Dragonslayer
  [184, "battle", false, 3], // Skybound Alchemist
  [185, "battle", false, 1], // Gate-Crushing Alchemist
  [186, "battle", false, 1], // Darkness-Smashing Alchemist
  [175, "battle", false, 3], // Skybound Fencer
  [176, "battle", false, 1], // Gate-Crushing Fencer
  [177, "battle", false, 1], // Darkness-Smashing Fencer
  [575, "battle", false, 3], // Skybound Spear
  [576, "battle", false, 1], // Gate-Crushing Spear
  [577, "battle", false, 1], // Darkness-Smashing Spear
  [578, "battle", false, 3], // Skybound Scythe
  [579, "battle", false, 1], // Gate-Crushing Scythe
  [580, "battle", false, 1], // Darkness-Smashing Scythe
  [633, "battle", false, 3], // Skybound Spirit Edge
  [634, "battle", false, 1], // Gate-Crushing Spirit Edge
  [635, "battle", false, 1], // Darkness-Smashing Spirit Edge
  [636, "battle", false, 3], // Skybound Dark Huntress
  [637, "battle", false, 1], // Gate-Crushing Dark Huntress
  [638, "battle", false, 1], // Darkness-Smashing Dark Huntress
  [669, "battle", false, 3], // Skybound Supreme Primarch
  [670, "battle", false, 1], // Gate-Crushing Primarch
  [671, "battle", false, 1], // Darkness-Smashing Primarch
  [187, "battle", false, 3], // Skybound Swordsman
  [188, "battle", false, 1], // Gate-Crushing Swordsman
  [189, "battle", false, 1], // Darkness-Smashing Swordsman
  [326, "gear", false, 6], // Captain's Collection
  [327, "gear", false, 6], // Captain's Trove
  [328, "gear", false, 6], // Katalina's Collection
  [329, "gear", false, 6], // Katalina's Trove
  [330, "gear", false, 6], // Rackam's Collection
  [331, "gear", false, 6], // Rackam's Trove
  [332, "gear", false, 6], // Io's Collection
  [333, "gear", false, 6], // Io's Trove
  [336, "gear", false, 6], // Eugen's Collection
  [337, "gear", false, 6], // Eugen's Trove
  [334, "gear", false, 6], // Rosetta's Collection
  [335, "gear", false, 6], // Rosetta's Trove
  [348, "gear", false, 6], // Charlotta's Collection
  [349, "gear", false, 6], // Charlotta's Trove
  [354, "gear", false, 6], // Ghandagoza's Collection
  [355, "gear", false, 6], // Ghandagoza's Trove
  [338, "gear", false, 6], // Ferry's Collection
  [339, "gear", false, 6], // Ferry's Trove
  [352, "gear", false, 6], // Narmaya's Collection
  [353, "gear", false, 6], // Narmaya's Trove
  [340, "gear", false, 6], // Lancelot's Collection
  [341, "gear", false, 6], // Lancelot's Trove
  [342, "gear", false, 6], // Vane's Collection
  [343, "gear", false, 6], // Vane's Trove
  [344, "gear", false, 6], // Percival's Collection
  [345, "gear", false, 6], // Percival's Trove
  [346, "gear", false, 6], // Siegfried's Collection
  [347, "gear", false, 6], // Siegfried's Trove
  [356, "gear", false, 6], // Cagliostro's Collection
  [357, "gear", false, 6], // Cagliostro's Trove
  [350, "gear", false, 6], // Yodarha's Collection
  [351, "gear", false, 6], // Yodarha's Trove
  [597, "gear", false, 6], // Zeta's Collection
  [598, "gear", false, 6], // Zeta's Trove
  [599, "gear", false, 6], // Vaseraga's Collection
  [600, "gear", false, 6], // Vaseraga's Trove
  [651, "gear", false, 2], // Seofon's Collection
  [652, "gear", false, 2], // Seofon's Trove
  [653, "gear", false, 2], // Tweyen's Collection
  [654, "gear", false, 2], // Tweyen's Trove
  [678, "gear", false, 2], // Wielder of Judgment's Blade
  [679, "gear", false, 2], // Master of Judgment's Blade
  [358, "gear", false, 6], // Id's Collection
  [359, "gear", false, 6], // Id's Trove
  [360, "gear", false, 10], // Bunch o' Pointy Things
  [361, "gear", false, 25], // Growing Arsenal
  [362, "gear", false, 50], // Lethal Weapons
  [363, "gear", false, 100], // Armed to the Teeth
  [364, "gear", false, 30], // Ironsmith
  [365, "gear", false, 100], // Bronzesmith
  [366, "gear", false, 1000], // Silversmith
  [367, "gear", false, 7500], // Goldsmith
  [368, "gear", false, 15000], // Grandsmith
  [369, "gear", false, 1], // Limit Breaker
  [1442, "gear", false, 1], // No Cap
  [370, "gear", false, 5], // Five Stars
  [371, "gear", false, 50], // Fifty Stars
  [372, "gear", false, 100], // One Hundred Stars
  [373, "gear", false, 300], // All the Stars
  [374, "gear", false, 1], // Available Everywhere
  [375, "gear", false, 1], // Not as Common
  [376, "gear", false, 1], // Rare Find
  [377, "gear", false, 1], // Pretty Epic
  [378, "gear", false, 1], // Stuff of Legends
  [601, "gear", false, 19], // Curator's Magnum Opus
  [657, "gear", false, 5], // Ultimate Spirit Edge
  [658, "gear", false, 5], // Unparalleled Huntress
  [681, "gear", false, 5], // Supreme Primarch
  [379, "gear", false, 10], // Sigil Casual
  [380, "gear", false, 50], // Sigil Collector
  [381, "gear", false, 100], // Sigil Fanatic
  [382, "gear", false, 1000], // Sigil Sense
  [383, "gear", false, 1], // Sigil Trainee
  [384, "gear", false, 25], // Sigil Researcher
  [385, "gear", false, 100], // Sigil Savant
  [386, "gear", false, 250], // Ask Me About My Sigils
  [387, "gear", false, 1], // Power of the Plus
  [388, "gear", false, 99], // Plus Ninety Nine
  [389, "gear", false, 200], // Plus Two Hundred
  [390, "gear", false, 500], // Plus Five Hundred
  [391, "gear", false, 5], // Favored by the Primeval Gods
  [392, "gear", false, 20], // Blessed by the Primeval Gods
  [393, "gear", false, 50], // Ordained by the Primeval Gods
  [394, "gear", false, 1], // Grand Skyfarer
  [395, "gear", false, 1], // Grand Guardian
  [396, "gear", false, 1], // Grand Helmsman
  [397, "gear", false, 1], // Grand Mage
  [399, "gear", false, 1], // Grand Sniper
  [398, "gear", false, 1], // Grand Rose
  [405, "gear", false, 1], // Grand Holy Knight
  [408, "gear", false, 1], // Grand Brawler
  [400, "gear", false, 1], // Grand Ghost
  [407, "gear", false, 1], // Grand Butterfly
  [401, "gear", false, 1], // Grand Twinfang
  [402, "gear", false, 1], // Grand Champion
  [403, "gear", false, 1], // Grand Lord
  [404, "gear", false, 1], // Grand Dragonslayer
  [409, "gear", false, 1], // Grand Alchemist
  [406, "gear", false, 1], // Grand Swordmaster
  [602, "gear", false, 1], // Grand Spear
  [603, "gear", false, 1], // Grand Scythe
  [655, "gear", false, 1], // Grand Seventh Eternal
  [656, "gear", false, 1], // Grand Second Eternal
  [680, "gear", false, 1], // Worldly Supreme Primarch
  [410, "gear", false, 1], // Grand Avenger
  [411, "gear", false, 5], // Awaken!
  [412, "gear", false, 10], // Thirst for Power
  [413, "gear", false, 15], // Waking the Armory
  [1403, "gear", false, 1], // True Potential
  [414, "gear", false, 1], // Fully Awake
  [415, "gear", false, 15], // Perfecting the Armory
  [605, "gear", false, 1], // Supreme Celestial
  [606, "gear", false, 1], // Supreme Refuge
  [607, "gear", false, 1], // Supreme Purifier
  [608, "gear", false, 1], // Supreme Coil
  [610, "gear", false, 1], // Supreme Dagger
  [609, "gear", false, 1], // Supreme Primal
  [616, "gear", false, 1], // Supreme Wrath
  [619, "gear", false, 1], // Supreme Fist
  [611, "gear", false, 1], // Supreme Beyond
  [618, "gear", false, 1], // Supreme Beheader
  [612, "gear", false, 1], // Supreme Unseen
  [613, "gear", false, 1], // Supreme Crusher
  [614, "gear", false, 1], // Supreme Fang
  [615, "gear", false, 1], // Supreme Blaze
  [620, "gear", false, 1], // Supreme Truth
  [617, "gear", false, 1], // Supreme Scales
  [621, "gear", false, 1], // Supreme Impaler
  [622, "gear", false, 1], // Supreme Doom
  [623, "gear", false, 1], // Supreme Sword
  [604, "gear", false, 1], // Approaching Supremacy
  [416, "other", false, 1], // Fateful Encounter
  [1446, "other", false, 1], // Welcome to the Crew
  [417, "other", false, 5], // Fateful Matchmaker
  [418, "other", false, 10], // This Crew Is Going Places
  [1400, "other", false, 19], // Squad's All Here
  [419, "other", false, 2500], // Flexing
  [420, "other", false, 5000], // Valorous
  [421, "other", false, 10000], // God Tier
  [422, "other", false, 5], // Veteran Crew
  [423, "other", false, 10], // Unrivaled Crew
  [424, "other", false, 5], // Glorious Crew
  [425, "other", false, 10], // God-Tier Crew
  [426, "other", false, 250], // To the Ends of the Skies
  [427, "other", false, 500], // Touched the Stars
  [428, "other", false, 1000], // Ruler of the Skies
  [1435, "other", false, 100], // Push It to the Limit
  [429, "other", false, 15], // Playing with All Aces
  [1444, "other", false, 1], // On the Road to Mastery
  [430, "other", false, 10], // First Steps
  [431, "other", false, 100], // Improving Steadily
  [432, "other", false, 300], // True Skill
  [433, "other", false, 500], // Absolute Mastery
  [624, "other", false, 19], // Completionist
  [442, "other", false, 1], // Vyrn's Bestest Pal
  [443, "other", false, 2], // Cherished by Lyria
  [444, "other", false, 3], // The Singularity
  [445, "other", false, 1], // Kat
  [446, "other", false, 2], // Chilling Beauty
  [447, "other", false, 3], // Ice to Meet You
  [448, "other", false, 1], // Smoking Gun
  [449, "other", false, 2], // Prodigious Helmsman
  [450, "other", false, 3], // The Crew's Compass
  [451, "other", false, 1], // High Standards
  [452, "other", false, 2], // Studious
  [453, "other", false, 3], // Magic Is Easy
  [457, "other", false, 1], // Tough as Nails
  [458, "other", false, 2], // Burdened by Regret
  [459, "other", false, 3], // Supreme Gunner
  [454, "other", false, 1], // Forest Beauty
  [455, "other", false, 2], // Captivation Incarnate
  [456, "other", false, 3], // Love Eternal
  [475, "other", false, 1], // Oh My Lumiel!
  [476, "other", false, 2], // Luminous Sword
  [477, "other", false, 3], // Tiny Radiance
  [484, "other", false, 1], // Disciples Wanted
  [485, "other", false, 2], // Rage for Breakfast
  [486, "other", false, 3], // Punch First, Questions Later
  [460, "other", false, 1], // Solitary Spirit
  [461, "other", false, 2], // Chosen Family
  [462, "other", false, 3], // Beast Tamer
  [481, "other", false, 1], // Meditating or Napping
  [482, "other", false, 2], // Asura
  [483, "other", false, 3], // Snow, Moon, and Flowers
  [463, "other", false, 1], // Secretly Untidy
  [464, "other", false, 2], // Too Handsome
  [465, "other", false, 3], // Meet the Twin Daggers
  [466, "other", false, 1], // Mongrel
  [467, "other", false, 2], // Stalwart Ally
  [468, "other", false, 3], // Shouldering Burdens
  [469, "other", false, 1], // Vassals Wanted
  [470, "other", false, 2], // Vermillion Noble
  [471, "other", false, 3], // Blade and Fire
  [472, "other", false, 1], // Mask of Justice
  [473, "other", false, 2], // Stained by Dragon Blood
  [474, "other", false, 3], // Dragon Soul
  [487, "other", false, 1], // Cutest in the World
  [488, "other", false, 2], // Possessor of Truth
  [489, "other", false, 3], // Height of Perfection
  [478, "other", false, 1], // Cleaver of Seas
  [479, "other", false, 2], // Don't Blink
  [480, "other", false, 3], // Ultimate Swordmaster
  [625, "other", false, 1], // Ducky
  [626, "other", false, 2], // Partners for Life
  [627, "other", false, 3], // Sweets or Death
  [628, "other", false, 1], // Scythe Therapy
  [629, "other", false, 2], // I'm Right Behind You
  [630, "other", false, 3], // Gentle Reaper
  [659, "other", false, 1], // Bottomless Potential
  [660, "other", false, 2], // I Am the World's Anchor
  [661, "other", false, 3], // Sky's Strongest Blade
  [662, "other", false, 1], // Nonconformist
  [663, "other", false, 2], // My Actions Do the Talking
  [664, "other", false, 3], // Queller of the Arcane Bow
  [682, "other", false, 1], // Shark Buster
  [683, "other", false, 2], // Coffee Buddy
  [684, "other", false, 3], // The Perfect Brew
  [490, "other", false, 1], // Awful with Machines
  [491, "other", false, 2], // On the Path to Atonement
  [492, "other", false, 3], // Penance or Bust
  [434, "other", false, 1], // Mastery Breaker
  [435, "other", false, 4], // Scaling Peaks
  [436, "other", false, 10], // Smashing Limits
  [437, "other", false, 15], // Shattering Skies
  [438, "other", false, 1], // Overpowered
  [439, "other", false, 4], // Over Overpowered
  [440, "other", false, 10], // Beyond Overpowered
  [441, "other", false, 15], // Overmastered
  [493, "other", false, 100], // Anima Maniac
  [494, "other", false, 250], // Super Anima Maniac
  [495, "other", false, 1000], // Ultimate Anima Maniac
  [1436, "other", false, 100000], // I Like It When Numbers Go Up
  [496, "other", false, 1000000], // Windfall
  [497, "other", false, 5000000], // Rich
  [498, "other", false, 10000000], // Filthy Rich
  [499, "other", false, 50000000], // One Percenter
  [500, "other", false, 10000], // Blacksmith Patron
  [501, "other", false, 100000], // Blacksmith Regular
  [502, "other", false, 1000000], // Blacksmith Benefactor
  [503, "other", false, 5000000], // VIP Customer
  [504, "other", false, 1], // First Investment
  [505, "other", false, 10], // Small-Time Trader
  [1443, "other", false, 10], // Knickknack Shack Regular
  [506, "other", false, 100], // Renowned Trader
  [507, "other", false, 300], // Siero's Protégé
  [508, "other", false, 1], // Novice Transmuter
  [509, "other", false, 10], // Pro Transmuter
  [510, "other", false, 100], // Master Transmuter
  [511, "other", false, 300], // Ascended Transmuter
  [687, "other", false, 1], // Look What I Made!
  [688, "other", false, 10], // Sigil Crafter
  [689, "other", false, 25], // Sigil Maestro
  [1445, "other", false, 10], // Making Ends Meet
  [512, "other", false, 1], // How Much for This?
  [1447, "other", false, 1], // On the House
  [513, "other", false, 10], // Curio Lovers Unite
  [514, "other", false, 100], // Part of the Family
  [515, "other", false, 250], // Have Curios, Will Trade
  [516, "other", false, 5], // Jackpot!
  [517, "other", false, 50], // Diamonds in the Rough
  [518, "other", false, 100], // Luck Be a Lady
  [519, "other", false, 1], // Daily Exercise
  [1441, "other", false, 1], // Practice Makes Perfect
  [520, "other", false, 10], // Training for Battle
  [521, "other", false, 25], // Bashing Sir Barrold
  [522, "other", false, 50], // Maximum Motivation
  [523, "other", false, 100000], // Buff Stuff
  [524, "other", false, 1000000], // It's Over 1,000,000!
  [525, "other", false, 10000000], // Now We're Dealing Damage
  [526, "other", false, 5000], // Speed Is My Forte
  [527, "other", false, 75000], // 10-Second Knockout
  [528, "other", false, 250000], // Speedrunner
  [529, "other", false, 25000], // Run and Gun
  [530, "other", false, 250000], // Game Changer
  [531, "other", false, 1000000], // Fleet Foot
  [532, "other", false, 50000], // Ace
  [533, "other", false, 500000], // Deal That Damage
  [534, "other", false, 2500000], // Strike Fast, Strike Hard
  [535, "other", false, 1], // Wishlister
  [536, "other", false, 5], // Treasure Seeker
  [537, "other", false, 10], // Feeling Greedy
  [538, "other", false, 20], // Materialistic
  [539, "other", false, 1], // Always Prepared
  [540, "other", false, 3], // Always Efficient
  [541, "other", false, 5], // Always Optimized
  [1415, "other", false, 1], // It's All About Communication
  [1402, "other", false, 1], // Reminiscence
  [1383, "other", false, 1], // Friends Forever
  [1384, "other", false, 1], // Feendrache's Pride
  [1389, "other", false, 10], // Photogenic
  [1391, "other", false, 5], // Cat Lover
  [1392, "other", false, 5], // Folca Birding Society
  [1390, "other", false, 10], // Gifted Photographer
  [1388, "other", false, 1], // Blue Steel!
  [1346, "other", false, 1], // We're in This Together
  [1347, "other", false, 2], // Happy to Help
  [1348, "other", false, 3], // Satisfaction Guaranteed
  [1354, "other", false, 1], // Can't Thank You Enough
  [1349, "other", false, 10000], // Your Friendly Neighborhood
  [1350, "other", false, 20000], // Premium Helper
  [1351, "other", false, 30000], // Special Mentor
  [1352, "other", false, 40000], // In High Demand
  [1353, "other", false, 50000], // High Roller
  [693, "other", false, 742], // Master of Relink
  [1394, "other", false, 53], // Platinum Sky
  [1532, "story", true, 1], // Wise One
  [1533, "story", true, 1], // Defier of Logic
  [1358, "story", true, 110], // Master of the Side Hustle
  [1359, "story", true, 8], // Archiver of Sky's Evolution
  [746, "story", true, 1], // Fearless
  [1468, "story", true, 1], // Welcome to the Club
  [747, "story", true, 1], // Chaos Mettle
  [1467, "story", true, 1], // Ragnalia Slayer
  [748, "story", true, 1], // Where No One Has Gone Before
  [1457, "story", true, 1], // On the Edge of Chaos
  [749, "story", true, 11], // Mover of Heaven and Earth
  [750, "story", true, 14], // Vanquisher of Fiends
  [751, "story", true, 26], // Chaos Dunker
  [752, "story", true, 51], // Broke the Grade Cap
  [762, "story", true, 1], // Contractor
  [1393, "story", true, 1], // Moon's No Longer Haunted
  [1387, "story", true, 1], // Rebel with a Cause
  [1454, "story", true, 1], // A Perfect World Realized
  [760, "story", true, 1], // Vanquisher of the Inchoate
  [1525, "story", true, 1], // Radiant Blue of Eternal Renown
  [1455, "story", true, 1], // The Eternals Got Nothing On Me
  [1453, "story", true, 1], // Conqueror of Flameborn Fate
  [758, "story", true, 1], // One-Winged Dragon
  [1452, "story", true, 1], // Destroyer of the Immortal
  [1530, "story", true, 1], // It's Good to Be King
  [1451, "story", true, 1], // Wings Beyond the Grand Finale
  [755, "story", true, 1], // Triple Zero
  [1526, "story", true, 1], // Surmounted the Chromatic Wings
  [1450, "story", true, 1], // Broke the Laws of Nature
  [1527, "story", true, 1], // Architect of My Own Providence
  [1456, "story", true, 3], // Extremely Excellent Execution
  [1448, "story", true, 4], // Endless Ragnarok
  [1624, "story", true, 1], // Starkiller
  [1622, "story", true, 1], // And We Have Killed Him
  [1626, "story", true, 1], // To Eternity and Beyond
  [1604, "story", true, 1], // Founder of a New World
  [1602, "story", true, 1], // Supreme King
  [1606, "story", true, 1], // Paradise Lost
  [1600, "story", true, 1], // Divine Deicide
  [1608, "story", true, 1], // Logos Prime
  [806, "story", true, 11], // Troublemaker
  [826, "story", true, 11], // Dog Rescuer
  [1536, "story", true, 11], // My Precious Star
  [1556, "story", true, 11], // The Missing Link
  [766, "story", true, 11], // Silver Wolf Guru
  [786, "story", true, 11], // Come Join My Tea Party
  [1478, "story", true, 6], // Wings of Fate
  [1355, "story", true, 20], // Fate Weaver
  [1356, "story", true, 25], // Fate Altruist
  [1357, "story", true, 28], // Evangelist
  [1342, "story", true, 1], // Hello, Dark Pince, My Old Friend
  [1488, "story", true, 1], // The Crabs in Black Do Exist!
  [1343, "story", true, 5], // Crabaholic
  [1344, "story", true, 10], // Crabblue Fantasy
  [1487, "story", true, 10], // Where the Wee Pincers Are
  [1345, "story", true, 20], // Got the Whole Whorl In My Hands
  [1466, "story", true, 20], // Life Is Shell
  [1580, "character", true, 30], // Prodigal Ultramarine
  [1581, "character", true, 60], // Immortal Saber
  [810, "character", true, 80], // Fury Road
  [811, "character", true, 100], // Resonating with Embrasque
  [812, "character", true, 1], // Never Take the L
  [813, "character", true, 100], // Leave Everything to Me!
  [814, "character", true, 100], // 2,000 Kcal
  [815, "character", true, 1], // I Am Immortal
  [1582, "character", true, 30], // Solitary Sniper
  [1583, "character", true, 60], // Thunder Scout
  [830, "character", true, 80], // Lightning Wolf
  [831, "character", true, 100], // Resonating with Flamek
  [832, "character", true, 1], // Dog Lover
  [833, "character", true, 100], // Polished Bullet
  [834, "character", true, 100], // Poker Face
  [835, "character", true, 1], // Cool and Composed
  [1584, "character", true, 30], // Twilight Dancer
  [1585, "character", true, 60], // Footloose and Radiant
  [1540, "character", true, 80], // Luminous Sage
  [1541, "character", true, 100], // The Strength Evoker
  [1542, "character", true, 1], // Beguiling Devil
  [1543, "character", true, 100], // Powered by Friendship
  [1544, "character", true, 100], // MISSING
  [1545, "character", true, 1], // Razzle-Dazzle
  [1586, "character", true, 30], // The Dark Has Eyes
  [1587, "character", true, 60], // Toxic
  [1560, "character", true, 80], // Black Dragon
  [1561, "character", true, 100], // Limitless Black
  [1562, "character", true, 1], // Wedge of the Sky
  [1563, "character", true, 100], // Show Me the Dyad
  [1564, "character", true, 100], // Life Steward
  [1565, "character", true, 1], // Total Eclipse
  [1576, "character", true, 30], // Rising Wolf
  [1577, "character", true, 60], // Storm General
  [770, "character", true, 80], // Absolute Mad Lancer
  [771, "character", true, 100], // 100-Star General
  [772, "character", true, 1], // Simply the Best
  [773, "character", true, 100], // Exuberant Pulverizer
  [774, "character", true, 100], // Mom's Home Cooking
  [775, "character", true, 1], // I Have No Equal
  [1578, "character", true, 30], // Etude of Daggers
  [1579, "character", true, 60], // Sword Maiden
  [790, "character", true, 80], // Octet Blade
  [791, "character", true, 100], // Realm-Famous Conductor
  [792, "character", true, 1], // Fabled Storyteller
  [793, "character", true, 100], // Saga Superiór
  [794, "character", true, 100], // Let Them Eat Pancake
  [795, "character", true, 1], // In Full Bloom
  [824, "character", true, 1], // I Roll with Beatrix
  [844, "character", true, 1], // I Roll with Eustace
  [1554, "character", true, 1], // I Roll with Fraux
  [1574, "character", true, 1], // I Roll with Fediel
  [784, "character", true, 1], // I Roll with Gallanza
  [804, "character", true, 1], // I Float with Maglielle
  [825, "character", true, 1], // Beatrix's Protégé
  [845, "character", true, 1], // Eustace's Protégé
  [1555, "character", true, 1], // Fraux's Deputy
  [1575, "character", true, 1], // Fediel's Adherent
  [785, "character", true, 1], // Gallanza's Adherent
  [805, "character", true, 1], // Maglielle's Deputy
  [847, "character", true, 10], // Chaos-Defying Skyfarer
  [848, "character", true, 30], // Hope-Inspiring Skyfarer
  [849, "character", true, 50], // Empyrean Skyfarer
  [850, "character", true, 1], // Blessed Skyfarer
  [851, "character", true, 1], // Transcendent Skyfarer
  [852, "character", true, 1], // Otherworldly Skyfarer
  [853, "character", true, 1], // Limit-Breaking Skyfarer
  [854, "character", true, 1], // Heart of the Sky
  [855, "character", true, 10], // Chaos-Defying Guardian
  [856, "character", true, 30], // Hope-Inspiring Guardian
  [857, "character", true, 50], // Empyrean Guardian
  [858, "character", true, 1], // Ice in My Veins
  [859, "character", true, 1], // Focused Fencer
  [860, "character", true, 1], // Harder than Diamond
  [861, "character", true, 1], // Limit-Breaking Guardian
  [862, "character", true, 1], // Oathsworn Blade
  [863, "character", true, 10], // Chaos-Defying Helmsman
  [864, "character", true, 30], // Hope-Inspiring Helmsman
  [865, "character", true, 50], // Empyrean Helmsman
  [866, "character", true, 1], // Soaring Gunslinger
  [867, "character", true, 1], // Boundless Voyager
  [868, "character", true, 1], // Shooting for the Stars
  [869, "character", true, 1], // Limit-Breaking Helmsman
  [870, "character", true, 1], // Noa's Bestie
  [871, "character", true, 10], // Chaos-Defying Mage
  [872, "character", true, 30], // Hope-Inspiring Mage
  [873, "character", true, 50], // Empyrean Mage
  [874, "character", true, 1], // Mage of Glory
  [875, "character", true, 1], // Healer of Hearts and Minds
  [876, "character", true, 1], // Spellslinging Phenom
  [877, "character", true, 1], // Limit-Breaking Mage
  [878, "character", true, 1], // Lady of Culture
  [887, "character", true, 10], // Chaos-Defying Sniper
  [888, "character", true, 30], // Hope-Inspiring Sniper
  [889, "character", true, 50], // Empyrean Sniper
  [890, "character", true, 1], // Soldier of Honor
  [891, "character", true, 1], // Sniper Extraordinaire
  [892, "character", true, 1], // Super Trooper
  [893, "character", true, 1], // Limit-Breaking Sniper
  [894, "character", true, 1], // Made a Vow to the Mother Sea
  [879, "character", true, 10], // Chaos-Defying Rose
  [880, "character", true, 30], // Hope-Inspiring Rose
  [881, "character", true, 50], // Empyrean Rose
  [882, "character", true, 1], // Primal Blossom
  [883, "character", true, 1], // Vine-Whip Dominator
  [884, "character", true, 1], // Exalted Bouquet
  [885, "character", true, 1], // Limit-Breaking Rose
  [886, "character", true, 1], // Rosa Damascena
  [935, "character", true, 10], // Chaos-Defying Holy Knight
  [936, "character", true, 30], // Hope-Inspiring Holy Knight
  [937, "character", true, 50], // Empyrean Holy Knight
  [938, "character", true, 1], // Crowning Achievement
  [939, "character", true, 1], // Towering over the Competition
  [940, "character", true, 1], // Exalted Paladin
  [941, "character", true, 1], // Limit-Breaking Holy Knight
  [942, "character", true, 1], // Enforcer of Justice
  [959, "character", true, 10], // Chaos-Defying Brawler
  [960, "character", true, 30], // Hope-Inspiring Brawler
  [961, "character", true, 50], // Empyrean Brawler
  [962, "character", true, 1], // Knockout King
  [963, "character", true, 1], // Meteor Buster
  [964, "character", true, 1], // Exalted Founder
  [965, "character", true, 1], // Limit-Breaking Brawler
  [966, "character", true, 1], // Godhand
  [895, "character", true, 10], // Chaos-Defying Ghost
  [896, "character", true, 30], // Hope-Inspiring Ghost
  [897, "character", true, 50], // Empyrean Ghost
  [898, "character", true, 1], // The Spice of Afterlife
  [899, "character", true, 1], // Ascendant Soul
  [900, "character", true, 1], // Spectacular Specter
  [901, "character", true, 1], // Limit-Breaking Ghost
  [902, "character", true, 1], // Ghost with the Most
  [951, "character", true, 10], // Chaos-Defying Butterfly
  [952, "character", true, 30], // Hope-Inspiring Butterfly
  [953, "character", true, 50], // Empyrean Butterfly
  [954, "character", true, 1], // Beautiful. Cheerful. Lethal.
  [955, "character", true, 1], // Swift-Edge Virtue
  [956, "character", true, 1], // Battlefield Monarch
  [957, "character", true, 1], // Limit-Breaking Butterfly
  [958, "character", true, 1], // One Hundred Cloudscapes
  [903, "character", true, 10], // Chaos-Defying Twinfang
  [904, "character", true, 30], // Hope-Inspiring Twinfang
  [905, "character", true, 50], // Empyrean Twinfang
  [906, "character", true, 1], // Ice Ice Lancey
  [907, "character", true, 1], // Twinblade Zenith
  [908, "character", true, 1], // Exalted Knight Captain
  [909, "character", true, 1], // Limit-Breaking Twinfang
  [910, "character", true, 1], // The Silver Blur
  [911, "character", true, 10], // Chaos-Defying Champion
  [912, "character", true, 30], // Hope-Inspiring Champion
  [913, "character", true, 50], // Empyrean Champion
  [914, "character", true, 1], // Bringing Home the Bacon
  [915, "character", true, 1], // Big-Hearted Paragon
  [916, "character", true, 1], // Everyone's Favorite Hero
  [917, "character", true, 1], // Limit-Breaking Champion
  [918, "character", true, 1], // Dauntless Fortress
  [919, "character", true, 10], // Chaos-Defying Lord
  [920, "character", true, 30], // Hope-Inspiring Lord
  [921, "character", true, 50], // Empyrean Lord
  [922, "character", true, 1], // All Hail
  [923, "character", true, 1], // Untamable Flame
  [924, "character", true, 1], // Immaculate Inferno
  [925, "character", true, 1], // Limit-Breaking Lord
  [926, "character", true, 1], // God of Flames
  [927, "character", true, 10], // Chaos-Defying Dragonslayer
  [928, "character", true, 30], // Hope-Inspiring Dragonslayer
  [929, "character", true, 50], // Empyrean Dragonslayer
  [930, "character", true, 1], // The Helmed Knight Rises
  [931, "character", true, 1], // Oblivion Cleaver
  [932, "character", true, 1], // Exalted Vanquisher
  [933, "character", true, 1], // Limit-Breaking Dragonslayer
  [934, "character", true, 1], // Dragon's Bane
  [967, "character", true, 10], // Chaos-Defying Alchemist
  [968, "character", true, 30], // Hope-Inspiring Alchemist
  [969, "character", true, 50], // Empyrean Alchemist
  [970, "character", true, 1], // You Can't Transmute Wisdom
  [971, "character", true, 1], // Beyond Evolutionary
  [972, "character", true, 1], // Genius at Work
  [973, "character", true, 1], // Limit-Breaking Alchemist
  [974, "character", true, 1], // Eternal Cutie
  [943, "character", true, 10], // Chaos-Defying Swordmaster
  [944, "character", true, 30], // Hope-Inspiring Swordmaster
  [945, "character", true, 50], // Empyrean Swordmaster
  [946, "character", true, 1], // Windslicing Dynamo
  [947, "character", true, 1], // Showing Minnows How It's Done
  [948, "character", true, 1], // Angler God
  [949, "character", true, 1], // Limit-Breaking Swordmaster
  [950, "character", true, 1], // Serene Sinker
  [975, "character", true, 10], // Chaos-Defying Spear
  [976, "character", true, 30], // Hope-Inspiring Spear
  [977, "character", true, 50], // Empyrean Spear
  [978, "character", true, 1], // Stick a Spear in It
  [979, "character", true, 1], // Blazing Highflyer
  [980, "character", true, 1], // Vaunted Vaulter
  [981, "character", true, 1], // Limit-Breaking Spear
  [982, "character", true, 1], // Shin Arvess
  [983, "character", true, 10], // Chaos-Defying Scythe
  [984, "character", true, 30], // Hope-Inspiring Scythe
  [985, "character", true, 50], // Empyrean Scythe
  [986, "character", true, 1], // Do Fear the Reaper
  [987, "character", true, 1], // Augmented Eclipse
  [988, "character", true, 1], // Exalted Berserker
  [989, "character", true, 1], // Limit-Breaking Scythe
  [990, "character", true, 1], // Shin Grynoth
  [1039, "character", true, 10], // Chaos-Defying Hellcat
  [1040, "character", true, 30], // Hope-Inspiring Hellcat
  [1041, "character", true, 50], // Empyrean Hellcat
  [1042, "character", true, 1], // Danger Is My Middle Name
  [1043, "character", true, 1], // Second Advent
  [1044, "character", true, 1], // Agent of Mayhem
  [1045, "character", true, 1], // Limit-Breaking Hellcat
  [1046, "character", true, 1], // Shin Embrasque
  [1047, "character", true, 10], // Chaos-Defying Commando
  [1048, "character", true, 30], // Hope-Inspiring Commando
  [1049, "character", true, 50], // Empyrean Commando
  [1050, "character", true, 1], // Faster than Lightning
  [1051, "character", true, 1], // Supercharged
  [1052, "character", true, 1], // Distinguished Service
  [1053, "character", true, 1], // Limit-Breaking Commando
  [1054, "character", true, 1], // Shin Flamek
  [991, "character", true, 10], // Chaos-Defying Spirit Edge
  [992, "character", true, 30], // Hope-Inspiring Spirit Edge
  [993, "character", true, 50], // Empyrean Spirit Edge
  [994, "character", true, 1], // Eternal Glory
  [995, "character", true, 1], // Trailblazing Swordplay
  [996, "character", true, 1], // World's Greatest Sword Collector
  [997, "character", true, 1], // Limit-Breaking Spirit Edge
  [998, "character", true, 1], // Celestial of the Blade
  [999, "character", true, 10], // Chaos-Defying Dark Huntress
  [1000, "character", true, 30], // Hope-Inspiring Dark Huntress
  [1001, "character", true, 50], // Empyrean Dark Huntress
  [1002, "character", true, 1], // Eyes on the Prize
  [1003, "character", true, 1], // Top of the Food Chain
  [1004, "character", true, 1], // Exalted Bowmaster
  [1005, "character", true, 1], // Limit-Breaking Dark Huntress
  [1006, "character", true, 1], // Celestial of the Hunt
  [1007, "character", true, 10], // Chaos-Defying Supreme Primarch
  [1008, "character", true, 30], // Hope-Inspiring Supreme Primarch
  [1009, "character", true, 50], // Empyrean Supreme Primarch
  [1010, "character", true, 1], // Glorious Halo
  [1011, "character", true, 1], // Wings of Evolution
  [1012, "character", true, 1], // Paradise Found
  [1013, "character", true, 1], // Limit-Breaking Supreme Primarch
  [1014, "character", true, 1], // Ain Soph Aur
  [1055, "character", true, 10], // Chaos-Defying Enchantress
  [1056, "character", true, 30], // Hope-Inspiring Enchantress
  [1057, "character", true, 50], // Empyrean Enchantress
  [1058, "character", true, 1], // Luminous Luminary
  [1059, "character", true, 1], // Four-Armed and Dangerous
  [1060, "character", true, 1], // Exalted Evoker
  [1061, "character", true, 1], // Limit-Breaking Enchantress
  [1062, "character", true, 1], // Bride of The Devil
  [1063, "character", true, 10], // Chaos-Defying Darkness
  [1064, "character", true, 30], // Hope-Inspiring Darkness
  [1065, "character", true, 50], // Empyrean Darkness
  [1066, "character", true, 1], // Embrace Darkness
  [1067, "character", true, 1], // Eclipsing Evolution
  [1068, "character", true, 1], // Exalted Dragon
  [1069, "character", true, 1], // Limit-Breaking Darkness
  [1070, "character", true, 1], // Ancestral
  [1015, "character", true, 10], // Chaos-Defying Avenger
  [1016, "character", true, 30], // Hope-Inspiring Avenger
  [1017, "character", true, 50], // Empyrean Avenger
  [1018, "character", true, 1], // Revel in Glorious Destruction
  [1019, "character", true, 1], // Mr. Break Id
  [1020, "character", true, 1], // Exalted Subjugator
  [1021, "character", true, 1], // Limit-Breaking Avenger
  [1022, "character", true, 1], // Versalis Heart
  [1023, "character", true, 10], // Chaos-Defying Gladiator
  [1024, "character", true, 30], // Hope-Inspiring Gladiator
  [1025, "character", true, 50], // Empyrean Gladiator
  [1026, "character", true, 1], // King of the Ring
  [1027, "character", true, 1], // Career Commander
  [1028, "character", true, 1], // Apex Skullcracker
  [1029, "character", true, 1], // Limit-Breaking Gladiator
  [1030, "character", true, 1], // Storming Death
  [1031, "character", true, 10], // Chaos-Defying Bladequeen
  [1032, "character", true, 30], // Hope-Inspiring Bladequeen
  [1033, "character", true, 50], // Empyrean Bladequeen
  [1034, "character", true, 1], // When I Talk, Everyone Listens
  [1035, "character", true, 1], // Nocturne of Superlatives
  [1036, "character", true, 1], // Exalted Maestro
  [1037, "character", true, 1], // Limit-Breaking Bladequeen
  [1038, "character", true, 1], // Symphony Superiór
  [753, "battle", true, 1], // Celestial Star
  [1610, "battle", true, 10], // Sumo Warrior
  [1611, "battle", true, 1], // Absolute Unit
  [1612, "battle", true, 1], // Yokozuna
  [1613, "battle", true, 1], // Celestial Squisher
  [1614, "battle", true, 5], // Slimeway to Heaven
  [1615, "battle", true, 10], // In Slime We Trust
  [1616, "battle", true, 30], // Red Baron
  [1617, "battle", true, 5], // Stranger Than Fiction
  [1618, "battle", true, 1], // Sushi Afishionado
  [759, "battle", true, 1], // Trionfi
  [761, "battle", true, 1], // New World Order
  [757, "battle", true, 1], // Horizon Breaker
  [1529, "battle", true, 1], // Steel Monarch
  [1531, "battle", true, 1], // Checkmate
  [754, "battle", true, 1], // Can't Stop, Won't Stop
  [756, "battle", true, 1], // Ø
  [1528, "battle", true, 1], // I AM THE LAW
  [1625, "battle", true, 1], // Automagod
  [1623, "battle", true, 1], // The Primeval
  [1627, "battle", true, 1], // Better than All the Rest
  [1605, "battle", true, 1], // The World
  [1603, "battle", true, 1], // Preeminent King
  [1607, "battle", true, 1], // Wings of Revelation
  [1601, "battle", true, 1], // There Can Only Be One
  [1609, "battle", true, 1], // Above the Law
  [1382, "battle", true, 300000], // Give It to Me, Baby
  [1489, "battle", true, 1], // All-Purpose Ether
  [807, "battle", true, 3], // Skybound Hellcat
  [808, "battle", true, 1], // Gate-Crushing Hellcat
  [809, "battle", true, 1], // Darkness-Smashing Hellcat
  [827, "battle", true, 3], // Skybound Commando
  [828, "battle", true, 1], // Gate-Crushing Commando
  [829, "battle", true, 1], // Darkness-Smashing Commando
  [1537, "battle", true, 3], // Skybound Enchantress
  [1538, "battle", true, 1], // Gate-Crushing Enchantress
  [1539, "battle", true, 1], // Darkness-Smashing Enchantress
  [1557, "battle", true, 3], // Skybound Darkness
  [1558, "battle", true, 1], // Gate-Crushing Darkness
  [1559, "battle", true, 1], // Darkness-Smashing Wedge
  [767, "battle", true, 3], // Skybound Gladiator
  [768, "battle", true, 1], // Gate-Crushing Gladiator
  [769, "battle", true, 1], // Darkness-Smashing Gladiator
  [787, "battle", true, 3], // Skybound Bladequeen
  [788, "battle", true, 1], // Gate-Crushing Bladequeen
  [789, "battle", true, 1], // Darkness-Smashing Bladequeen
  [816, "gear", true, 6], // Beatrix's Collection
  [817, "gear", true, 6], // Beatrix's Trove
  [836, "gear", true, 6], // Eustace's Collection
  [837, "gear", true, 6], // Eustace's Trove
  [1546, "gear", true, 4], // Fraux's Collection
  [1547, "gear", true, 4], // Fraux's Trove
  [1566, "gear", true, 4], // Fediel's Collection
  [1567, "gear", true, 4], // Fediel's Trove
  [776, "gear", true, 4], // Gallanza's Collection
  [777, "gear", true, 4], // Gallanza's Trove
  [796, "gear", true, 4], // Maglielle's Collection
  [797, "gear", true, 4], // Maglielle's Trove
  [1360, "gear", true, 120], // Drowning in Weapons
  [1361, "gear", true, 150], // Weapons Enthusiast
  [1362, "gear", true, 154], // Walking Armory
  [820, "gear", true, 4], // Ultramarine
  [840, "gear", true, 4], // Thunderwolf
  [1550, "gear", true, 4], // In a World of My Own
  [1570, "gear", true, 4], // Law of Darkness
  [780, "gear", true, 4], // Big Rad Wolf
  [800, "gear", true, 4], // Making It Rain Blades
  [1485, "gear", true, 1], // My Evil Eye Approves!
  [818, "gear", true, 1], // Grand Hellcat
  [838, "gear", true, 1], // Grand Commando
  [1548, "gear", true, 1], // Grand Enchantress
  [1568, "gear", true, 1], // Grand Darkness
  [778, "gear", true, 1], // Grand Gladiator
  [798, "gear", true, 1], // Grand Bladequeen
  [819, "gear", true, 1], // Supreme Maverick
  [839, "gear", true, 1], // Supreme Trigger
  [763, "gear", true, 1], // Supreme Seven-Edge
  [764, "gear", true, 1], // Supreme Two-Arrow
  [765, "gear", true, 1], // Supreme Terminus
  [1549, "gear", true, 1], // Supreme Hellblaze
  [1569, "gear", true, 1], // Supreme Dark Wedge
  [779, "gear", true, 1], // Supreme Duelseeker
  [799, "gear", true, 1], // Supreme Virtuosa
  [1071, "gear", true, 7], // Aspiring Dreamer
  [1075, "gear", true, 7], // Meteora
  [1074, "gear", true, 7], // Stay Blue
  [1073, "gear", true, 7], // Big Tuna
  [1072, "gear", true, 7], // Courageous
  [1076, "gear", true, 7], // Ruination
  [1077, "gear", true, 6], // True Legend
  [1078, "gear", true, 7], // Tenacious
  [1082, "gear", true, 7], // Protector of the Blue
  [1081, "gear", true, 7], // Ephemeral
  [1080, "gear", true, 7], // Blade of Light
  [1079, "gear", true, 7], // Mirage
  [1083, "gear", true, 7], // Unyielding
  [1084, "gear", true, 6], // Legendary Guardian
  [1085, "gear", true, 7], // Full of Ambition
  [1089, "gear", true, 7], // Horizon's Bullet
  [1088, "gear", true, 7], // Gunsmoke
  [1087, "gear", true, 7], // Hurricane
  [1086, "gear", true, 7], // Flak and Slash
  [1090, "gear", true, 7], // No Scope 360 Headshot
  [1091, "gear", true, 6], // Knife to a Gun Fight
  [1092, "gear", true, 7], // Tireless Seeker
  [1096, "gear", true, 7], // Virtuous Heart
  [1095, "gear", true, 7], // Uplifter
  [1094, "gear", true, 7], // Hellfire
  [1093, "gear", true, 7], // Twin Serpent
  [1097, "gear", true, 7], // Miracle Worker
  [1098, "gear", true, 6], // I'm a Wand-erkind
  [1106, "gear", true, 7], // Tide Turner
  [1110, "gear", true, 7], // Penitent
  [1109, "gear", true, 7], // I Speak My Mind
  [1108, "gear", true, 7], // Hail of Bullets
  [1107, "gear", true, 7], // Incendiary
  [1111, "gear", true, 7], // Roaring Dragon
  [1112, "gear", true, 6], // Big Guns Expert
  [1099, "gear", true, 7], // Oblivion
  [1103, "gear", true, 7], // Forget-Me-Not
  [1102, "gear", true, 7], // Red Spider Lily
  [1101, "gear", true, 7], // Sunflower
  [1100, "gear", true, 7], // Snapdragon
  [1104, "gear", true, 7], // Wall of Thorns
  [1105, "gear", true, 6], // That's the Power of Love
  [1148, "gear", true, 7], // In the Name of Glory
  [1152, "gear", true, 7], // Righteous Fury
  [1151, "gear", true, 7], // Eradicator of Evil
  [1150, "gear", true, 7], // Passionate
  [1149, "gear", true, 7], // Never Say Never
  [1153, "gear", true, 7], // Victorious
  [1154, "gear", true, 6], // More Humble than Thou Art
  [1169, "gear", true, 7], // Red Fist
  [1173, "gear", true, 7], // Goldfinger
  [1172, "gear", true, 7], // Fist of the Star
  [1171, "gear", true, 7], // Throw Up the Horns
  [1170, "gear", true, 7], // Rope-a-Dope
  [1174, "gear", true, 7], // Sting Like an Oni
  [1175, "gear", true, 6], // You Are Already Dead
  [1113, "gear", true, 7], // Join Me in the Spirit Realm
  [1117, "gear", true, 7], // Unfurled Possibilities
  [1116, "gear", true, 7], // Snap Reflexes
  [1115, "gear", true, 7], // Blazing Jump Roper
  [1114, "gear", true, 7], // Genuine
  [1118, "gear", true, 7], // Nebulous
  [1119, "gear", true, 6], // The Whipping Dead
  [1162, "gear", true, 7], // Butterfly Effect
  [1166, "gear", true, 7], // Imperious
  [1165, "gear", true, 7], // Selfless
  [1164, "gear", true, 7], // Blue Aster
  [1163, "gear", true, 7], // Tiger Swallowtail
  [1167, "gear", true, 7], // Bladed Beauty
  [1168, "gear", true, 6], // Way of the Blademaster
  [1120, "gear", true, 7], // The Bold and the Dutiful
  [1124, "gear", true, 7], // Ever Loyal
  [1123, "gear", true, 7], // Allow Me to Break the Ice
  [1122, "gear", true, 7], // Relentless
  [1121, "gear", true, 7], // Cocytus
  [1125, "gear", true, 7], // Hidden Blade
  [1126, "gear", true, 6], // Two Swords Are Better than One
  [1127, "gear", true, 7], // Steadfast
  [1131, "gear", true, 7], // When a Hero Comes Along
  [1130, "gear", true, 7], // Chic
  [1129, "gear", true, 7], // I'm Electrifying
  [1128, "gear", true, 7], // Swan Song
  [1132, "gear", true, 7], // Bringing the Thunder
  [1133, "gear", true, 6], // Axe-cellent
  [1134, "gear", true, 7], // Royal
  [1138, "gear", true, 7], // King Me
  [1137, "gear", true, 7], // Naturally Gifted
  [1136, "gear", true, 7], // Ode to Greatness
  [1135, "gear", true, 7], // Cardinal
  [1139, "gear", true, 7], // You Shall Bend the Knee
  [1140, "gear", true, 6], // Long May I Reign
  [1141, "gear", true, 7], // Honor Bound
  [1145, "gear", true, 7], // Calamitous
  [1144, "gear", true, 7], // Ashes to Ashes
  [1143, "gear", true, 7], // Bloodstained
  [1142, "gear", true, 7], // I'm a Survivor
  [1146, "gear", true, 7], // Slayer of Fortune
  [1147, "gear", true, 6], // Master of the Greatsword
  [1176, "gear", true, 7], // So Cute It Hurts
  [1180, "gear", true, 7], // Unabridged
  [1179, "gear", true, 7], // Etched in History
  [1178, "gear", true, 7], // Taboo
  [1177, "gear", true, 7], // Essential Reading
  [1181, "gear", true, 7], // Great Sage
  [1182, "gear", true, 6], // Killer Librarian
  [1155, "gear", true, 7], // The Honorable
  [1159, "gear", true, 7], // Immovable
  [1158, "gear", true, 7], // Blade of the Phantasm
  [1157, "gear", true, 7], // Nightsong
  [1156, "gear", true, 7], // Super Ashura
  [1160, "gear", true, 7], // Fish Sticks
  [1161, "gear", true, 6], // Illusory Swiftblade
  [1183, "gear", true, 7], // Scorching Hot
  [1187, "gear", true, 7], // Annihilator
  [1186, "gear", true, 7], // Heavenly Pillar
  [1185, "gear", true, 7], // Karma
  [1184, "gear", true, 7], // Solar Flare
  [1188, "gear", true, 7], // Rebel
  [1189, "gear", true, 6], // The Impaler
  [1190, "gear", true, 7], // Ethereal Darkness
  [1194, "gear", true, 7], // Soul Shepherd
  [1193, "gear", true, 7], // Daybreak
  [1192, "gear", true, 7], // Perdition
  [1191, "gear", true, 7], // Gift of Love
  [1195, "gear", true, 7], // Acrimonious
  [1196, "gear", true, 6], // Reapers Gonna Reap
  [1229, "gear", true, 7], // Nothing Can Stop Me
  [1233, "gear", true, 7], // Ready to Rumble
  [1232, "gear", true, 7], // Dragonheart
  [1231, "gear", true, 7], // Helmsplitter
  [1230, "gear", true, 7], // Firebrand
  [1234, "gear", true, 7], // Cleaver
  [1235, "gear", true, 6], // Embrasque's Champion
  [1236, "gear", true, 7], // Raging Lightning
  [1240, "gear", true, 7], // Punisher
  [1239, "gear", true, 7], // Supernova
  [1238, "gear", true, 7], // Ready and Willing
  [1237, "gear", true, 7], // Incognito
  [1241, "gear", true, 7], // Seek and Destroy
  [1242, "gear", true, 6], // Man with the Electric Gun
  [1197, "gear", true, 7], // Perfect Ten
  [1199, "gear", true, 7], // Stellar
  [1198, "gear", true, 7], // Tempest
  [1200, "gear", true, 7], // One Sword to Rule Them All
  [1201, "gear", true, 4], // Oops! All Swords
  [1202, "gear", true, 7], // Elegy
  [1204, "gear", true, 7], // Revenant Ray
  [1203, "gear", true, 7], // Labor of Love
  [1205, "gear", true, 7], // One Bow to Rule Them All
  [1206, "gear", true, 4], // Master of Arrow-Dynamics
  [1207, "gear", true, 7], // Free of Sin
  [1209, "gear", true, 7], // Vengeful
  [1208, "gear", true, 7], // Fire
  [1210, "gear", true, 7], // Sunshine
  [1211, "gear", true, 4], // Keeper of Promises
  [1243, "gear", true, 7], // Made a Deal with The Devil
  [1245, "gear", true, 7], // Eyes on Me
  [1244, "gear", true, 7], // Dancing Queen
  [1246, "gear", true, 7], // Knockout Beauty
  [1247, "gear", true, 4], // Kick Ass
  [1248, "gear", true, 7], // Cursed Ivy
  [1250, "gear", true, 7], // Corpse Flower
  [1249, "gear", true, 7], // I Wear My Sunglasses at Night
  [1251, "gear", true, 7], // Genesis
  [1252, "gear", true, 4], // Master of Darkness's Domain
  [1212, "gear", true, 7], // It's the End of the World
  [1216, "gear", true, 7], // Epic
  [1215, "gear", true, 7], // The Comeback Kid
  [1214, "gear", true, 7], // Premium Prodigy
  [1213, "gear", true, 7], // Blade of Avia
  [1217, "gear", true, 7], // World Dominator
  [1218, "gear", true, 6], // Greatsworder of Death
  [1219, "gear", true, 7], // Spear of Avia
  [1221, "gear", true, 7], // Disaster Mode
  [1220, "gear", true, 7], // Nice to Beat You
  [1222, "gear", true, 7], // Number One
  [1223, "gear", true, 4], // Iron-Willed General
  [1224, "gear", true, 7], // Conjurer of Avia
  [1226, "gear", true, 7], // Grand Arbiter
  [1225, "gear", true, 7], // Fire of Purification
  [1227, "gear", true, 7], // My Fair Lady
  [1228, "gear", true, 4], // Blade Dance Master Class
  [1483, "gear", true, 1], // Overhaul!
  [1463, "gear", true, 1], // 13 Uncaps
  [1594, "conflux", true, 1], // Hole Plugger of Seedhollow
  [1595, "conflux", true, 1], // Shut It Down!
  [1253, "conflux", true, 1], // Interdimensional Inquisitor
  [1470, "conflux", true, 1], // This Is My Chaos
  [1254, "conflux", true, 1], // Entropy Explorer
  [1469, "conflux", true, 1], // Passed Prelims
  [1255, "conflux", true, 1], // I Sit on the Chaos Throne
  [1256, "conflux", true, 1], // Apex Conqueror
  [1449, "conflux", true, 1], // Wings that Subjugated Chaos
  [1258, "conflux", true, 1], // All According to Keikaku
  [1257, "conflux", true, 1], // Demon King
  [1260, "conflux", true, 1], // Get Out of My Way
  [1261, "conflux", true, 10], // Passion for Strife
  [1262, "conflux", true, 30], // A Force to Be Reckoned With
  [1266, "conflux", true, 1], // Whatever Doesn't Kill Me...
  [1267, "conflux", true, 5], // Last One Standing
  [1268, "conflux", true, 10], // Survival of the Fittest
  [1269, "conflux", true, 1], // Remorseless
  [1270, "conflux", true, 5], // Like a Hot Knife Through Butter
  [1271, "conflux", true, 10], // Do Not Pursue
  [1619, "conflux", true, 1], // The Valiant
  [1620, "conflux", true, 5], // IYKYK
  [1621, "conflux", true, 10], // Rising Star
  [1275, "conflux", true, 1], // Demons and Spirits, Oh My!
  [1277, "conflux", true, 1], // Nameless
  [1278, "conflux", true, 3], // Bob
  [1279, "conflux", true, 10], // One of Us! One of Us!
  [1280, "conflux", true, 1], // Traceur
  [1281, "conflux", true, 3], // Phantom Rock Collector
  [1282, "conflux", true, 10], // Run like the Wind
  [1597, "conflux", true, 1], // Purple Haze
  [1283, "conflux", true, 1], // Slime Catcher
  [1284, "conflux", true, 3], // I Ain't Takin' No Plain DMG
  [1285, "conflux", true, 10], // No Respect These Days
  [1286, "conflux", true, 15], // Drowsy Drew
  [1598, "conflux", true, 1], // Slime Chaser
  [1287, "conflux", true, 1], // In the Liminal Zone
  [1288, "conflux", true, 3], // They're the Same Picture
  [1289, "conflux", true, 10], // I Came, I Saw, I Discovered
  [1290, "conflux", true, 1], // Chief Inspector
  [1599, "conflux", true, 1], // Möbius Walker
  [1472, "conflux", true, 1], // Ike Ike Danchou!
  [1276, "conflux", true, 4], // Built for Gaming
  [1473, "conflux", true, 4], // Ganbare Ganbare Danchou!
  [1471, "conflux", true, 100], // Frequent Confluxer
  [1259, "conflux", true, 1], // I Love You All!
  [1474, "conflux", true, 1], // This Thing's Rigged!
  [1341, "conflux", true, 1], // Sushi Chef
  [1461, "conflux", true, 1], // Whoa-Whoa Yeaaah!
  [1339, "conflux", true, 100000000], // Of Course Fish Fly
  [1340, "conflux", true, 350000000], // Fatty Tuna
  [1291, "conflux", true, 8000000], // Gate of Chaos
  [1292, "conflux", true, 10000000], // Realmbreaker
  [1293, "conflux", true, 15000000], // At the Top of My Game
  [1458, "conflux", true, 10000000], // Can't Beat My High Score
  [1462, "conflux", true, 50], // Chaos Kid
  [1459, "conflux", true, 1], // I'll Make This Quick!
  [1460, "conflux", true, 1], // Memento Mori
  [1477, "conflux", true, 30000], // Points Expert
  [1294, "conflux", true, 15], // Vitality Hoarder
  [1295, "conflux", true, 15], // Sequestration Hoarder
  [1296, "conflux", true, 15], // Fortification Hoarder
  [1297, "conflux", true, 15], // Dread Hoarder
  [1298, "conflux", true, 15], // Destruction Hoarder
  [1299, "conflux", true, 15], // Warfare Hoarder
  [1300, "conflux", true, 16], // Calamity Hoarder
  [1301, "conflux", true, 12], // Chaos Hoarder
  [1302, "conflux", true, 15], // Vitality Buff
  [1303, "conflux", true, 15], // Sequestration Buff
  [1304, "conflux", true, 15], // Fortification Buff
  [1305, "conflux", true, 15], // Dread Buff
  [1306, "conflux", true, 15], // Rebirth and Destruction
  [1307, "conflux", true, 15], // Warfare Buff
  [1308, "conflux", true, 16], // Salvation Buff
  [1309, "conflux", true, 12], // Chaos Buff
  [1310, "conflux", true, 236], // I Survived the Conflux
  [1475, "conflux", true, 18], // Go! Go! Pow! Pow!
  [1476, "conflux", true, 4], // More... More!
  [1311, "conflux", true, 3], // Coronated Skyfarer
  [1312, "conflux", true, 3], // Coronated Guardian
  [1313, "conflux", true, 3], // Coronated Helmsman
  [1314, "conflux", true, 3], // Coronated Mage
  [1316, "conflux", true, 3], // Coronated Sniper
  [1315, "conflux", true, 3], // Coronated Rose
  [1322, "conflux", true, 3], // Coronated Holy Knight
  [1325, "conflux", true, 3], // Coronated Brawler
  [1317, "conflux", true, 3], // Coronated Ghost
  [1324, "conflux", true, 3], // Coronated Butterfly
  [1318, "conflux", true, 3], // Coronated Twinfang
  [1319, "conflux", true, 3], // Coronated Champion
  [1320, "conflux", true, 3], // Coronated Lord
  [1321, "conflux", true, 3], // Coronated Dragonslayer
  [1326, "conflux", true, 3], // Coronated Alchemist
  [1323, "conflux", true, 3], // Coronated Swordmaster
  [1327, "conflux", true, 3], // Coronated Spear
  [1328, "conflux", true, 3], // Coronated Scythe
  [1335, "conflux", true, 3], // Coronated Hellcat
  [1336, "conflux", true, 3], // Coronated Commando
  [1329, "conflux", true, 3], // Coronated Spirit Edge
  [1330, "conflux", true, 3], // Coronated Dark Huntress
  [1331, "conflux", true, 3], // Coronated Supreme Primarch
  [1337, "conflux", true, 3], // Coronated Enchantress
  [1338, "conflux", true, 3], // Coronated Darkness
  [1332, "conflux", true, 3], // Coronated Avenger
  [1333, "conflux", true, 3], // Coronated Gladiator
  [1334, "conflux", true, 3], // Coronated Bladequeen
  [1494, "summons", true, 1], // Let's Network
  [1495, "summons", true, 50], // Followers +50
  [1496, "summons", true, 100], // Followers +100
  [1497, "summons", true, 200], // Followers +200
  [1490, "summons", true, 1], // Doppelgänger Commander
  [1491, "summons", true, 50], // Pure Summoner
  [1492, "summons", true, 100], // Sum 100
  [1493, "summons", true, 200], // Divine Caller
  [1499, "summons", true, 10], // Bound by Fate
  [1500, "summons", true, 50], // Voice of the Universe
  [1501, "summons", true, 100000000], // Omega Summoner
  [1502, "summons", true, 250000000], // Ultimate Summoner
  [1503, "summons", true, 1000000000], // Super Ultimate Summoner
  [1510, "summons", true, 200000], // Medic!
  [1511, "summons", true, 1000000], // Someone Call for a Doctor?
  [1512, "summons", true, 5000000], // Healing Hand
  [1507, "summons", true, 4], // Everyone Needs Supplements
  [1508, "summons", true, 20], // Buff Summoner
  [1509, "summons", true, 40], // Captain of the Cheer Squad
  [1504, "summons", true, 5], // Jamming Is My Jam
  [1505, "summons", true, 25], // What Sorcery Is This?!
  [1506, "summons", true, 50], // Hex Maniac
  [1514, "summons", true, 1], // Acolyte of Mellose
  [1513, "summons", true, 1], // Zathba's Favorite
  [1517, "summons", true, 6], // Dragonspeaker
  [1515, "summons", true, 1], // Mr. Fix It on Call
  [1516, "summons", true, 1], // Zealot of Avia
  [1521, "summons", true, 3], // Cat Whisperer
  [1522, "summons", true, 3], // I'm a Crab
  [1520, "summons", true, 3], // God of the Sea
  [1518, "summons", true, 4], // Child of the Primeval Gods
  [1523, "summons", true, 20], // Shaman of Salvation
  [1519, "summons", true, 1], // Catastrophe Incarnate
  [1524, "summons", true, 1], // Not Afraid of Anything Anymore
  [1479, "other", true, 1], // Mission Is a Go
  [1481, "other", true, 1], // Strong and Beautiful
  [1482, "other", true, 1], // The Black of the Six Dragons
  [1480, "other", true, 3], // Enemies Yesterday, Friends Today
  [1363, "other", true, 35000], // Rampage
  [1364, "other", true, 40000], // Dominating
  [1365, "other", true, 45000], // Unstoppable
  [1366, "other", true, 50000], // Godlike
  [1367, "other", true, 55000], // Impossible
  [1368, "other", true, 15], // Battle-Tested Crew
  [1369, "other", true, 15], // First-Class Crew
  [1370, "other", true, 20], // Untouchable Crew
  [1371, "other", true, 20], // Excelsior Crew
  [1372, "other", true, 28], // Realm-Bending Crew
  [1486, "other", true, 1], // Get On My Level, Newcomers
  [821, "other", true, 1], // I Get Paid in Donuts
  [822, "other", true, 2], // Sweet Tooth
  [823, "other", true, 3], // The Undying Blue
  [841, "other", true, 1], // Give Me Peace and Quiet
  [842, "other", true, 2], // Society Elite
  [843, "other", true, 3], // Lone Wolf
  [1551, "other", true, 1], // Mystery Girl
  [1552, "other", true, 2], // I'm No Quitter
  [1553, "other", true, 3], // Making Friends Along the Way
  [1571, "other", true, 1], // Curious like a Dragon
  [1572, "other", true, 2], // Free Spirit
  [1573, "other", true, 3], // Researcher of Mortal Culture
  [781, "other", true, 1], // World's Strongest Man
  [782, "other", true, 2], // Mwahaha!
  [783, "other", true, 3], // Fortune Favors the Bold
  [801, "other", true, 1], // Un, Deux, Trois
  [802, "other", true, 2], // Tea-aholic
  [803, "other", true, 3], // May I Have This Sword Dance?
  [1373, "other", true, 1000000000], // It's Over 1,000,000,000!
  [1374, "other", true, 500000], // Breakneck Speed
  [1375, "other", true, 1000000], // 2 Fast 2 Injurious
  [1376, "other", true, 5000000], // Half-Minute Smackdown
  [1377, "other", true, 10000000], // Flash and Fury
  [1378, "other", true, 20000000], // Training Overlord
  [1379, "other", true, 50000000], // God in 60 Seconds
  [1385, "other", true, 1], // Elite Beatdown Agents
  [1534, "other", true, 1], // Call of the Arcarum
  [1535, "other", true, 1], // Step Forth, Beyond the Blue
  [1386, "other", true, 1], // Family, Family, Family
  [846, "other", true, 1], // Nexus of Potential
  [1484, "other", true, 1], // To Be a Master
  [1464, "other", true, 50], // Level Overflow
  [1465, "other", true, 5], // It's Peak
];
